#pragma once

#include "updates.h"

// 游戏基址
#define MMOCLIENT_REVERSAL_GAME_ADDR			UPDATES_MMOCLIENT_REVERSAL_GAME_ADDR		// 8B0D????????8B49??8B118B42??FFD08B108BC88B82????????57FFD08B4E??85C9
#define MMOCLIENT_REVERSAL_GAME_OFFSET1			UPDATES_MMOCLIENT_REVERSAL_GAME_OFFSET1
#define MMOCLIENT_REVERSAL_GAME_OFFSET2			UPDATES_MMOCLIENT_REVERSAL_GAME_OFFSET2

// 发包部分
#define MMOCLIENT_REVERSAL_SOCKET_BASE_ADDR		UPDATES_MMOCLIENT_REVERSAL_SOCKET_BASE_ADDR  
#define MMOLCINET_REVERSAL_SOCKET_OFFSET1		UPDATES_MMOLCINET_REVERSAL_SOCKET_OFFSET1  
#define MMOCLIENT_REVERSAL_SOCKET_OFFSET2		UPDATES_MMOLCINET_REVERSAL_SOCKET_OFFSET2  
#define MMOCLIENT_REVERSAL_SOCKET_OFFSET3		UPDATES_MMOCLIENT_REVERSAL_SOCKET_OFFSET3  

// #define MMOCLIENT_REVERSAL_SOCKET_OFFSET3		UPDATES_MMOCLIENT_REVERSAL_SOCKET_OFFSET3
// #define MMOCLIENT_REVERSAL_SOCKET_OFFSET4		UPDATES_MMOCLIENT_REVERSAL_SOCKET_OFFSET4
// #define MMOCLIENT_REVERSAL_SOCKET_OFFSET5		UPDATES_MMOCLIENT_REVERSAL_SOCKET_OFFSET5
#define MMOCLIENT_REVERSAL_SEND_CALL			UPDATES_MMOCLIENT_REVERSAL_SEND_CALL		// hook游戏发包
#define MMOCLIENT_REVERSAL_SEND_CALL2			UPDATES_MMOCLIENT_REVERSAL_SEND_CALL2		// 程序发包

//走路封包需要的一个动态值
// #define MMOCLIENT_REVERSAL_WALK_DYNAMEIC_OFFSET1	UPDATES_MMOCLIENT_REVERSAL_WALK_DYNAMEIC_OFFSET1
// #define MMOCLIENT_REVERSAL_WALK_DYNAMEIC_OFFSET2	UPDATES_MMOCLIENT_REVERSAL_WALK_DYNAMEIC_OFFSET2
// #define MMOCLIENT_REVERSAL_WALK_DYNAMEIC_OFFSET3	UPDATES_MMOCLIENT_REVERSAL_WALK_DYNAMEIC_OFFSET3

// 遍历对象
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_OFFSET3			UPDATES_MMOCLIENT_REVERSAL_TRAVERSE_OBJ_OFFSET3
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_OFFSET4___		0x1C

#define MMOCLIENT_REVERSAL_TRAVERSAL_OBJ_XYZ_OFFSET_CLASS___		0x4			// class
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFSET___				0x0c		// 遍历坐标对象的偏移
#define MMOCLIENT_REVERSAL_TRAVERSAL_OBJ_STATUS_OFFSET___			0x1AC		// 对象战斗状态

#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_LOCAL_ID_OFSET___			0x10		// 本地id
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_DIR_OFFSET___				0x4C		// 攻击对象时，修改部位的同时需要修改角色坐标和角色面向
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_ACTOR_VECTOR_OFFSET___	0x60		// 坐标和方向的偏移
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_ACTOR_VECTOR2_OFFSET___	0x38		// 核心修改坐标
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFFSET_NAME___			0xEC		// 名字偏移
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFSET_PACKET_ID___		0xF8 		// 封包id

#define MMOCLIENT_REVERSAL_LIE_SHOU_XU_KE_ZHENG_COUNT_OFFSET1		UPDATES_MMOCLIENT_REVERSAL_LIE_SHOU_XU_KE_ZHENG_COUNT_OFFSET1  		// 副本剩余次数

// 角色经验
#define MMOCLIENT_REVERSAL_ROLE_EXP_OFFSET1					UPDATES_MMOCLIENT_REVERSAL_ROLE_EXP_OFFSET1  
#define MMOCLIENT_REVERSAL_ROLE_SINGLE_EXP_OFFSET___		0x14F0    // 先遣
#define MMOCLIENT_REVERSAL_ROLE_DOUBLE_EXP_OFFSET___		0x1A38	  // 先遣
#define MMOCLIENT_REVERSAL_ROLE_CUR_EXP_OFFSET___			0x5C	  // 先遣
#define MMOCLIENT_REVERSAL_ROLE_MEMORY_BANG_DING_OFFSET		UPDATES_MMOCLIENT_REVERSAL_ROLE_MEMORY_BANG_DING_OFFSET  
#define MMOCLIENT_REVERSAL_ROLE_MEMORY_LIU_TONG_OFFSET		UPDATES_MMOCLIENT_REVERSAL_ROLE_MEMORY_LIU_TONG_OFFSET  
//#define MMOCLIENT_REVERSAL_ROLE_MEMORY_LIE_BI_OFFSET		UPDATES_MMOCLIENT_REVERSAL_ROLE_MEMORY_LIE_BI_OFFSET  
#define MMOCLIENT_REVERSAL_ROLE_MEMORY_JING_SUAN_DIAN_OFFSET		UPDATES_MMOCLIENT_REVERSAL_ROLE_MEMORY_JING_SUAN_DIAN_OFFSET	// 精算点
#define MMOCLIENT_REVERSAL_ROLE_ZHAN_WEI_ZHI_OFFSET			UPDATES_MMOCLIENT_REVERSAL_ROLE_ZHAN_WEI_ZHI_OFFSET  	// 斩味值
#define MMOCLIENT_REVERSAL_ROLE_LIAN_QI_CAO_OFFSET			UPDATES_MMOCLIENT_REVERSAL_ROLE_LIAN_QI_CAO_OFFSET  	// 炼气槽
#define MMOCLIENT_REVERSAL_ROLE_ZHONG_DU_STATE_OFFSET___	0x2118+4*0x0a+0xA0		// 中毒状态偏移  中毒=1 正常=0
#define MMOCLIENT_REVERSAL_ROLE_ENCRYPTION_LEVEL_OFFSET___	0xC				// 加密的角色等级


// 庄园id
#define MMOCLIENT_REVERSAL_ACTOR_ZHUANG_YUAN_ID_OFFSET		UPDATES_MMOCLIENT_REVERSAL_ACTOR_ZHUANG_YUAN_ID_OFFSET  


// npc name
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFSET_NAME1___	0x104
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFSET_NAME2___	0x40
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFSET_NAME3___	0x18
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFSET_NAME4		UPDATES_MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFSET_NAME4  
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFSET_NAME5___		0x18+4
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFSET_NPC_TYPE___	0x1C+4		// npc细分类型的数据
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFSET_TITLE5___	0x74		// 称号偏移1
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_XYZ_OFFSET_TITLE6___	0			// 称号偏移2

#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_ROOM_IXDEX_OFFSET___	0x2C		// 对象所在房间序号

// 通过id获取对象的二叉树循环遍历CALL
#define MMOCLIENT_REVERSAL_GET_ACTOR_OBJADDR_CALL		 UPDATES_MMOCLIENT_REVERSAL_GET_ACTOR_OBJADDR_CALL

// 攻击封包需要用到的随机数据
#define MMOCLIENT_REVERSAL_GAME_RAND_BASE_ADDR		UPDATES_MMOCLIENT_REVERSAL_GAME_RAND_BASE_ADDR
#define MMOCLIENT_REVERSAL_GAME_RAND_OFFSET1___		0x164

// 角色属性
#define MMOCLIENT_REVERSAL_ACTOR_OFFSET1		UPDATES_MMOCLIENT_REVERSAL_ACTOR_OFFSET1  
#define MMOCLIENT_REVERSAL_ACTOR_OFFSET2		UPDATES_MMOCLIENT_REVERSAL_ACTOR_OFFSET2  
#define MMOCLIENT_REVERSAL_ACTOR_OFFSET3___		0x214

// 角色所在地图名字
#define MMOCLIENT_REVERSAL_ACTOR_IN_MAP_OFFFSET2		UPDATES_MMOCLIENT_REVERSAL_ACTOR_IN_MAP_OFFFSET2
#define MMOCLIENT_REVERSAL_ACTOR_IN_MAP_OFFFSET3___		0x1C

// 角色所在线路
#define MMOCLIENT_REVERSAL_ACTOR_OFFSET_XIAN_LU		UPDATES_MMOCLIENT_REVERSAL_ACTOR_OFFSET_XIAN_LU
#define MMOCLIENT_REVERSAL_ACTOR_OFFSET_ID___		0x8
#define MMOCLIENT_REVERSAL_ACTOR_LEVEL_OFFSET		UPDATES_MMOCLIENT_REVERSAL_ACTOR_LEVEL_OFFSET  	// 角色等级

// 使用技能CALL
#define MMOCLIENT_REVERSAL_SKILL_CALL			UPDATES_MMOCLIENT_REVERSAL_SKILL_CALL
#define MMOCLIENT_REVERSAL_SKILL_OFFSET			UPDATES_MMOCLIENT_REVERSAL_SKILL_OFFSET

// hook 收包
#define MMOCLIENT_REVERSAL_RECV_HOOK			UPDATES_MMOCLIENT_REVERSAL_RECV_HOOK


// 解密CALL
#define MMOCLIENT_REVERSAL_DECRY_CALL			UPDATES_MMOCLIENT_REVERSAL_DECRY_CALL
// 加密CALL
#define MMOCLIENT_REVERSAL_ENCRYPTION_CALL		UPDATES_MMOCLIENT_REVERSAL_ENCRYPTION_CALL

// hook 代码段，eax返回主窗口句柄
#define MMOCLIENT_REVERSAL_GAME_CREATEWINDOW_HOOK		UPDATES_MMOCLIENT_REVERSAL_GAME_CREATEWINDOW_HOOK

// 遍历背包，仓库，装备
#define MMOCLIENT_REVERSAL_TRAVERSE_GE_ZI_OFFSET1				UPDATES_MMOCLIENT_REVERSAL_TRAVERSE_GE_ZI_OFFSET1
#define MMOCLIENT_REVERSAL_TRAVERSE_GE_ZI_ITEM_OFFSET1___		0x0C			// 背包物品
#define MMOCLIENT_REVERSAL_TRAVERSE_GE_ZI_EQUIP_OFFSET1___		0x18			// 装备物品
#define MMOCLIENT_REVERSAL_TRAVERSE_GE_ZI_CANG_KU_OFFSET1___	0x14			// 普通仓库
#define MMOCLIENT_REVERSAL_TRAVERSE_GE_ZI_TASK_OFFSET1___		0x20			// 任务物品	
#define MMOCLIENT_REVERSAL_TRAVERSE_GE_ZI_CANG_KU_SU_CAI_OFFSET1___	0x34		// 素材仓库

#define MMOCLIENT_REVERSAL_TRAVERSE_GE_ZI_COUNT_OFFSET___	0x08		// 有效格子数量
#define MMOCLIENT_REVERSAL_TRAVERSE_ITEM_COUNT_OFFSET__		0x08		// 物品数量
#define MMOCLIENT_REVERSAL_TRAVERSE_ITEM_OFFSET1___			0x18
#define MMOCLIENT_REVERSAL_TRAVERSE_ITEM_OFFSET2___			0x8

#define MMOCLIENT_REVERSAL_TRAVERSE_ITEM_OBJ_COUNT_OFFSET___	0x3C+0x10
#define MMOCLIENT_REVERSAL_TRAVERSE_ITEM_OBJ_ADDR_OFFSET___		0x08
#define MMOCLIENT_REVERSAL_TRAVERSE_ITME_OBJ_NAME_OFFSET___		0x14
#define MMOCLIENT_REVERSAL_TRAVERSE_ITEM_PACKET_ID_OFFSET___		0x11C
#define MMOCLIENT_REVERSAL_TRAVERSE_ITEM_PACKET_KEY1_OFFSET___		0x10
#define MMOCLIENT_REVERSAL_TRAVERSE_ITEM_PACKET_KEY2_OFFSET___		0x14
#define MMOCLIENT_REVERSAL_TRAVERSE_ITEM_OBJ_BANG_DING_OFFSET___	0x28		// 物品是否绑定，非模板地址偏移

#define MMOCLIENT_REVERSAL_ITEM_LEVEL_OFFSET___						0x28		// 物品等级
#define MMOCLIENT_REVERSAL_ITEM_YONG_YOU_SHANG_XIAN_OFFSET___		0x30		// 拥有上限
#define MMOCLIENT_REVERSAL_ITEM_YAN_SE_OFFSET___					0x34		// 物品颜色，表示等级
#define MMOCLIENT_REVERSAL_ITEM_XIE_DAI_SHANG_XIAN_OFFSET___		0x38		// 携带上限
#define MMOCLIENT_REVERSAL_ITEM_DUI_DIE_SHANG_XIAN_OFFSET___		0x3C		// 堆叠上限
#define MMOCLIENT_REVERSAL_ITEM_WU_PIN_LEI_XING_OFFSET___			0x1C		// 物品类型，用去区分装备和消耗品之类
#define MMOCLIENT_REVERSAL_ITEM_BU_WEI_LEI_XING_OFFSET___			0x20		// 部位类型，用去区分武器和防具
#define MMOCLIENT_REVERSAL_ITEM_WU_PIN_LEI_XING_SUO_OFFSET___		0x24 		// 物品类型，需要解锁的标志
#define MMOCLIENT_REVERSAL_ITME_USE_LEVEL_OFFSET___					0xAC		// 角色使用物品需要的等级
#define MMOCLIENT_REVERSAL_ITEM_PACKET_ID_OFFSET___					0x10		// 取补给箱物品时用到的id
#define MMOCLIENT_REVERSAL_ITEM_WU_PIN_FEN_JIE_OFFSET___			0x84		// 是否可分解物品

// 升级装备信息
#define MMOCLIENT_REVERSAL_ITEM_UP_EQUIP_INFO_ADDR_OFFSET___		0x1B8	//0x198
#define MMOCLIENT_REVERSAL_ITEM_UP_EQUIP_MATERIAL_INFO_OFFFSET___	0x1C

// 怪物血值hook
#define MMOCLIENT_REVERSAL_MONSTER_HP_CALL_HOOK				UPDATES_MMOCLIENT_REVERSAL_MONSTER_HP_CALL_HOOK  
//#define MMOCLIENT_REVERSAL_MONSTER_HP_CALL_CMP_ADDR		UPDATES_MMOCLIENT_REVERSAL_MONSTER_HP_CALL_CMP_ADDR		// 调用修改怪物血值的上一层
#define MMOCLIENT_REVERSAL_MONSTER_HP_CALL_CMP_ADDR2		UPDATES_MMOCLIENT_REVERSAL_MONSTER_HP_CALL_CMP_ADDR2  
#define MMOCLIENT_REVERSAL_MONSTER_HP_ADDR_OFFSET1___		0x04
#define MMOCLIENT_REVERSAL_MONSTER_HP_PACKET_ID_OFFSET___	0x04

// 玩家血值hook
#define MMOCLIENT_REVERSAL_ACTOR_FEEB_HP_CALL_HOOK			UPDATES_MMOCLIENT_REVERSAL_ACTOR_FEEB_HP_CALL_HOOK     // 虚弱的减血加血	
#define MMOCLIENT_REVERSAL_ACTOR_HIT_HP_CALL_HOOK			UPDATES_MMOCLIENT_REVERSAL_ACTOR_HIT_HP_CALL_HOOK  	 // 直接的减血加血

// 根据id获取ui文字
#define MMOCLIENT_REVERSAL_GET_MU_BAN_INFO_ADDR_CALL		UPDATES_MMOCLIENT_REVERSAL_GET_UI_INFO_ADDR_CALL  
#define MMOCLIENT_REVERSAL_GET_UI_INFO_BASE_ADDR_CALL		UPDATES_MMOCLIENT_REVERSAL_GET_UI_INFO_BASE_ADDR_CALL  

// 任务信息
#define MMOCLIENT_REVERSAL_GET_TASK_OBJ_ADDR_CALL			UPDATES_MMOCLIENT_REVERSAL_GET_TASK_OBJ_ADDR_CALL  
#define MMOCLIENT_REVERSAL_TASK_OBJ_OFFSET1					UPDATES_MMOCLIENT_REVERSAL_TASK_OBJ_OFFSET1  	// 0x18
#define MMOCLIENT_REVERSAL_TASK_NAME_OFFSET___				0x8
#define MMOCLIENT_REVERSAL_TASK_TYPE_OFFSET___				0x10
#define MMOCLIENT_REVERSAL_TASK_COMPLETE_OFFSET___			0x14
#define MMOCLIENT_REVERSAL_TASK_RECEVIED_NPC_NAME_OFFSET1		UPDATES_MMOCLIENT_REVERSAL_TASK_RECEVIED_NPC_NAME_OFFSET1  
#define MMOCLIENT_REVERSAL_TASK_RECEVIED_NPC_NAME_OFFSET2		UPDATES_MMOCLIENT_REVERSAL_TASK_RECEVIED_NPC_NAME_OFFSET2  	//0x18
#define MMOCLIENT_REVERSAL_TASK_REWARD_ITEM_OFFSET___				0x4C
#define MMOCLIENT_REVERSAL_TASK_REWARD_ITEM_CMP_VALUE___			0x1000	// 用来区分是地址和数据的，只有奖励物品，才是地址 

#define MMOCLIENT_REVERSAL_TASK_LEVEL_ADDR_OFFSET1___		0x20	// 任务可接受的等级信息  只有在1-99之间的等级任务方为正常
#define MMOCLIENT_REVERSAL_TASK_LEVEL_ADDR_OFFSET2___		0x4
#define MMOCLIENT_REVERSAL_TASK_MIN_LEVEL_OFFSET___			0x0
#define MMOCLIENT_REVERSAL_TASK_MAX_LEVEL_OFFSET___			0x4

// CryMalloc 清0 hook地址
#define MMOCLIENT_REVERSAL_CRYMALLOC_FUNADDR				UPDATES_MMOCLIENT_REVERSAL_CRYMALLOC_FUNADDR  

// 已接任务基址
#define MMOCLIENT_REVERSAL_TASK_BASE_ADDR					UPDATES_MMOCLIENT_REVERSAL_TASK_BASE_ADDR  
#define MMOCLIENT_REVERSAL_TASK_BASE_OFFSET1___				0x10

#define MMOCLIENT_REVERSAL_RECEIVED_TASK_INFO_ADDR___		0x08
#define MMOCLIENT_REVERSAL_RECEIVED_TASK_TRUE_OFFSET___		0x1C

// 可接任务的判断
#define MMOCLIENT_REVERSAL_GAME_OBJ_ADDR			UPDATES_MMOCLIENT_REVERSAL_GAME_OBJ_ADDR  
#define MMOCLIENT_REVERSAL_GAME_OBJ_CALL			UPDATES_MMOCLIENT_REVERSAL_GAME_OBJ_CALL		// 通过id获取对象的地址

#define MMOCLIENT_REVERSAL_GAME_OBJ_OFFSET1					UPDATES_MMOCLIENT_REVERSAL_GAME_OBJ_OFFSET1  
#define MMOCLINET_REVERSAL_GAME_GET_CAN_ACCPET_TASK_CALL	UPDATES_MMOCLINET_REVERSAL_GAME_GET_CAN_ACCPET_TASK_CALL	

/*#define MMOCLIENT_REVERSAL_GAME_OBJ_TASK_ADDR		UPDATES_MMOCLIENT_REVERSAL_GAME_OBJ_TASK_ADDR  */

#define MMOCLIENT_REVERSAL_DO_TASK_DST_OFFSET1___		0x40
#define MMOCLIENT_REVERSAL_DO_TASK_DST_OFFSET2___		0x14
#define MMOCLIENT_REVERSAL_DO_TASK_DST_FB_ID_OFFSET1___	0x20
#define MMOCLIENT_REVERSAL_DO_TASK_DST_FB_ID_OFFSET2___	0x0C

// hook 模板信息基址
#define MMOCLIENT_REVERSAL_INFO_HOOK				UPDATES_MMOCLIENT_REVERSAL_INFO_HOOK  

// 遍历游戏内的一些大的对象
#define MMOCLIENT_REVERSAL_TRAVERSAL_ALL_OBJ_ADDR			UPDATES_MMOCLIENT_REVERSAL_TRAVERSAL_ALL_OBJ_ADDR  
#define MMOCLIENT_REVERSAL_TRAVERSAL_ALL_OBJ_OFFSET			UPDATES_MMOCLIENT_REVERSAL_TRAVERSAL_ALL_OBJ_OFFSET  
#define MMOCLIENT_REVERSAL_TRAVERSAL_OBJ_MSG_NAME___		0x18

// 能够遍历到游戏内所有实现对象
#define MMOCLIENT_REVERSAL_TRAVERSAL_SINGLE_OBJ_OFFSET1		UPDATES_MMOCLIENT_REVERSAL_TRAVERSAL_SINGLE_OBJ_OFFSET1  
#define MMOCLIENT_REVERSAL_TRAVERSAL_SINGLE_OBJ_OFFSET2		UPDATES_MMOCLIENT_REVERSAL_TRAVERSAL_SINGLE_OBJ_OFFSET2  

// 获取采集对象地址的虚函数表偏移，取消无效封包的宏特征码
// #define MMOCLIENT_REVERSAL_COLLECT_VFUN_ADDR_OFFSET1		UPDATES_MMOCLIENT_REVERSAL_COLLECT_VFUN_ADDR_OFFSET1  
// #define MMOCLIENT_REVERSAL_COLLECT_VFUN_ADDR_OFFSET2		UPDATES_MMOCLIENT_REVERSAL_COLLECT_VFUN_ADDR_OFFSET2  
//#define MMOCLIENT_REVERSAL_COLLECT_PACKET_ID_OFFSET			UPDATES_MMOCLIENT_REVERSAL_COLLECT_PACKET_ID_OFFSET  

// 采集对象在房间序号的偏移
#define MMOCLIENT_REVERSAL_TRAVERSE_COLLECT_ROOM_INDEX_OFFSET1___		0x188+0x10
#define MMOCLIENT_REVERSAL_TRAVERSE_COLLECT_ROOM_INDEX_OFFSET2___		0x50

// 采集物品新的遍历
#define MMOCLIENT_REVERSAL_COLLECT_OBJ_OFFSET1___		0x04
#define MMOCLIENT_REVERSAL_COLLECT_OBJ_OFFSET2___		0x0C
#define MMOCLIENT_REVERSAL_COLLECT_OBJ_ID_OFFSET___		0x04
#define MMOCLIENT_REVERSAL_COLLECT_OBJ_NODE_ADDR_OFFSET___	0x08
#define MMOCLIENT_REVERSAL_COLLECT_OBJ_XYZ_OFFSET___		0x60
#define MMOCLIENT_REVERSAL_COLLECT_OBJ_NAME_OFFSET___		0x28
#define MMOCLIENT_REVERSAL_COLLECT_OBJ_MONSTER_PACKET_ID_OFFSET		UPDATES_MMOCLIENT_REVERSAL_COLLECT_OBJ_MONSTER_PACKET_ID_OFFSET   // 怪物尸体的归属对象id
#define MMOCLIENT_REVERSAL_COLLECT_ZHEN_DE_DUI_XIANG_OFFSET___		0x2C
#define MMOCLIENT_REVERSAL_COLLECT_ITEM_ADDR_OFFSET___				0x34

// 遍历采集对象和怪物对象的中文名字
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_NAME1_OFFSET___		0x44
#define MMOCLIENT_REVERSAL_TRAVERSE_OBJ_NAME2_OFFSET___		0x160	//	0x158


#define MMOCLIENT_REVERSAL_DOOR_IN_ROOM_INDEX_OFFSET___		0x110+0x0C	// 遍历门对象的房间序号
#define MMOCLIENT_REVERSAL_DOOR_IN_ROOM_LINK_OFFSET___		0xB4	// 遍历门对象的link字符串，判断门是否有效的标志


// 遍历副本的信息
//#define MMOCLIENT_REVERSAL_GET_FB_BASE_ADDR_CALL		UPDATES_MMOCLIENT_REVERSAL_GET_FB_BASE_ADDR_CALL  
#define MMOCLIENT_REVERSAL_GET_FB_INFO_ADDR_CALL		UPDATES_MMOCLIENT_REVERSAL_GET_FB_INFO_ADDR_CALL  
#define MMOCLIENT_REVERSAL_IN_FB_INFO_OFFSET1			UPDATES_MMOCLIENT_REVERSAL_IN_FB_INFO_OFFSET1  
#define MMOCLIENT_REVERSAL_IN_FB_INFO_OFFSET2___		0x8
#define MMOCLIENT_REVERSAL_FB_INFO_NAME_OFFSET___		0x1C
#define MMOCLIENT_REVERSAL_FB_INFO_LEVEL_OFFSET___		0x38
#define MMOCLIENT_REVERSAL_FB_INFO_MAP_ID_OFFSET___		0x14

// 根据物品id获取物品的信息
#define MMOCLIENT_REVERSAL_GET_ITEM_INFO_ADDR_CALL		UPDATES_MMOCLIENT_REVERSAL_GET_ITEM_INFO_ADDR_CALL  

// 使用物品
#define MMOCLIENT_REVERSAL_USE_ITEM_OBJ_ADDR				UPDATES_MMOCLIENT_REVERSAL_USE_ITEM_OBJ_ADDR  
#define MMOCLIENT_REVERSAL_USE_ITEM_TAB_INDEX_OFFSET___		0x24
#define MMOCLIENT_REVERSAL_USE_ITEM_SLOT_INDEX_OFFSET___	0x28
#define MMOCLIENT_REVERSAL_USE_ITEM_TRIGGER_FLAG_OFFSET___	0x3C

// 地图加载完的代码地址
#define MMOCLIENT_REVERSAL_LOAD_MAP_END_HOOK			UPDATES_MMOCLIENT_REVERSAL_LOAD_MAP_END_HOOK		// 加载城镇地图
#define MMOCLIENT_REVERSAL_LOAD_MAP_END_HOOK2			UPDATES_MMOCLIENT_REVERSAL_LOAD_MAP_END_HOOK2		// 加载副本地图

// 邮件遍历
#define MMOCLIENT_REVERSAL_MAIL_OFFSET1				UPDATES_MMOCLIENT_REVERSAL_MAIL_OFFSET1  
#define MMOCLIENT_REVERSAL_MAIL_OFFSET2___			0x6C  
#define MMOCLIENT_REVERSAL_MAIL_ID_OFFSET1___		0x00
#define MMOCLIENT_REVERSAL_MAIL_ID_OFFSET2___		0x04
//#define MMOCLIENT_REVERSAL_MAIL_ADDR_OFFSET___		0x18
#define MMOCLIENT_REVERSAL_MAIL_SENDER_OFFSET___	0x2C		// 发邮件人
#define MMOCLIENT_REVERSAL_MAIL_TITLE_OFFSET___		0x5C		// 标题
#define MMOCLIENT_REVERSAL_MAIL_GOLD_OFFSET___		0x8C		// 金币
#define MMOCLIENT_REVERSAL_MAIL_ATTACH_ITEM_OFFSET___			0xA4
#define MMOCLIENT_REVERSAL_MAIL_ATTACH_ITEM_COUNT_OFFSET___		0x10
#define MMOCLIENT_REVERSAL_MAIL_ATTACH_ITEM_ID_OFFSET___		0x14
#define MMOCLIENT_REVERSAL_MAIL_ATTACH_ITEM_SIZE___				0x20

// 鼠标键盘
#define MMOCLIENT_REVERSAL_GWLR_WINDOWS_BASE_ADDR			UPDATES_MMOCLIENT_REVERSAL_GWLR_WINDOWS_BASE_ADDR  
#define MMOCLIENT_REVERSAL_MOUSE_LBUTTONDOWN_OFFSET1		UPDATES_MMOCLIENT_REVERSAL_MOUSE_LBUTTONDOWN_OFFSET1  
#define MMOCLIENT_REVERSAL_MOUSE_LBUTTONDOWN_OFFSET2___		0x10
#define MMOCLIENT_REVERSAL_LBUTTONDOWN		1		// 鼠标左键
#define MMOCLIENT_REVERSAL_LBUTTONUP		2		// 鼠标右键


// 猎守副本结束后的提示部分代码hook
#define MMOCLIENT_REVERSAL_FB_GAME_OVER_HOOK		UPDATES_MMOCLIENT_REVERSAL_FB_GAME_OVER_HOOK  
#define MMOCLIENT_REVERSAL_FB_GAME_OVER_WIN_HOOK	UPDATES_MMOCLIENT_REVERSAL_FB_GAME_OVER_WIN_HOOK  		// 战斗结束, 你胜利了
#define MMOCLIENT_REVERSAL_FB_GAME_OVER_LOSE_HOOK	UPDATES_MMOCLIENT_REVERSAL_FB_GAME_OVER_LOSE_HOOK  		// 战斗结束, 你失败了


// 商品遍历
#define MMOCLIENT_REVERSAL_GET_EQUIP_INF0_BASE_ADDR_CALL		UPDATES_MMOCLIENT_REVERSAL_GET_EQUIP_INF0_BASE_ADDR_CALL  
#define MMOCLIENT_REVERSAL_GET_SHOP_INFO_OFFSET___			0x1C
#define MMOCLIENT_REVERSAL_SHOP_INFO_SIZE___				0x68
#define MMOCLIENT_REVERSAL_SHOP_INFO_SHOP_ID_OFFSET___		0x8
#define MMOCLIENT_REVERSAL_SHOP_INFO_ITEM_ID_OFFSET___		0x28
#define MMOCLIENT_REVERSAL_SHOP_INFO_ITEM_COUNT_OFFSET___	0x2C

// 锻造物品的遍历
#define MMOCLIENT_REVERSAL_GET_CRAFT_INFO_ADDR_CALL			UPDATES_MMOCLIENT_REVERSAL_GET_CRAFT_INFO_ADDR_CALL  
#define MMOCLIENT_REVERSAL_CRAFT_INFO_CRAFT_ID_OFFSET___	0x10
#define MMOCLIENT_REVERSAL_CRAFT_INFO_ITEM_ID_OFFSET___		0x44
#define MMOCLIENT_REVERSAL_CRAFT_INF0_MATERIAL_OFFSET___	0x78
#define MMOCLIENT_REVERSAL_MATERIAL_SIZE___		0x8


// 副本模板信息
#define MMOCLIENT_REVERSAL_ATCOR_IN_MAP_FB_ID_OFFSET___				0x10
#define MMOCLIENT_REVERSAL_ACTOR_IN_MAP_MU_BAN_ID_OFFSET___			0x14
#define MMOCLIENT_REVERSAL_ACTOR_IN_MAP_MU_BAN_ADDR_OFFSET___		0x18
#define MMOCLIENT_REVERSAL_ACTOR_IN_MAP_MU_BAN_ADDR_NAME_OFFSET___	0x28

// 优化动画
// #define MMOCLIENT_REVERSAL_OPTIMIZE_CUTSCENE_HOOK		UPDATES_MMOCLIENT_REVERSAL_OPTIMIZE_CUTSCENE_HOOK 
// #define MMOCLIENT_REVERSAL_OPTIMIZE_CUTSCENE_HOOK2___	0x005F205B		// 无效

// CPU优化
#define MMOCLIENT_REVERSAL_RENDER_ADDR_HOOK		UPDATES_MMOCLIENT_REVERSAL_RENDER_ADDR_HOOK

// DX按键
#define MMOCLIENT_REVERSAL_DX_KEYBOARD_PRESS_BASE_ADDR		UPDATES_MMOCLIENT_REVERSAL_DX_KEYBOARD_PRESS_BASE_ADDR  
#define MMOCLIENT_REVERSAL_DX_KEYBOARD_PRESS_OFFSET1___		0x48
#define MMOCLIENT_REVERSAL_DX_KEYBOARD_PRESS_OFFSET2___		0x0
#define MMOCLIENT_REVERSAL_DX_KEYBOARD_PRESS_CALL			UPDATES_MMOCLIENT_REVERSAL_DX_KEYBOARD_PRESS_CALL  

// 多倍攻击CALL
#define MMOCLIENT_REVERSAL_HIT_CALL_HOOK		UPDATES_MMOCLIENT_REVERSAL_HIT_CALL_HOOK  
#define MMOCLIENT_REVERSAL_HIT_CALL				UPDATES_MMOCLIENT_REVERSAL_HIT_CALL  
#define MMOCLIENT_REVERSAL_HIT_BASE_ADDR		UPDATES_MMOCLIENT_REVERSAL_HIT_BASE_ADDR  
#define MMOCLINET_REVERSAL_GONG_JI_BU_WEI_OFFSET___			0x48			// 多倍攻击函数的参数一的攻击部位偏移
#define MMOCLIENT_REVERSAL_TEST_CHECK_GONG_JI_BU_WEI___		0x000000CA		// 每个副本内都存在一个测试对象，而这个对象极有可能是用来检测本地是不是被处理掉了，此对象会每隔一段时间，就往服务器发送一个攻击封包的内容，但封包不属于攻击封包

// 无敌
//#define MMOCLIENT_REVERSAL_MONSTER_HIT_ADDR_HOOK			UPDATES_MMOCLIENT_REVERSAL_MONSTER_HIT_ADDR_HOOK		// 老的无敌，在新的无敌hook的前面，或许后面会用到，注释下
#define MMOCLIENT_REVERSAL_MONSTER_HIT_ADDR_HOOK			UPDATES_MMOCLIENT_REVERSAL_MONSTER_HIT_ADDR_HOOK2      //E8 8112C500     CALL MHOClien.01275588                   ; 攻击函数 hook 处理无敌
#define MMOCLIENT_REVERSAL_MONSTER_HIT_ADDR_CALL			UPDATES_MMOCLIENT_REVERSAL_MONSTER_HIT_ADDR_CALL2  
// 远程无敌
#define MMOCLIENT_REVERSAL_MONSTER_REMOTE_HIT_ADDR_HOOK			UPDATES_MMOCLIENT_REVERSAL_MONSTER_REMOTE_HIT_ADDR_HOOK  
#define MMOCLIENT_REVERSAL_MONSTER_REMOTE_HIT_OBJ_OFFSET___		0x18


// 返回角色界面的执行代码
#define MMOCLIENT_REVERSAL_RET_ROLE_CHOOSE_JIE_MIAN_HOOK	UPDATES_MMOCLIENT_REVERSAL_RET_ROLE_CHOOSE_JIE_MIAN_HOOK

// hook剧情，用于剧情判断
#define MMOCLIENT_REVERSAL_SPRINTF_JU_QING_STRING_HOOK			UPDATES_MMOCLIENT_REVERSAL_SPRINTF_JU_QING_STRING_HOOK  
#define MMOCLIENT_REVERSAL_SPRINTF_JU_QING_STRING_OFFSET___		0x14

// 查询拍卖物品的返回封包数据，对封包数据进行解密获取物品id的函数
#define MMOCLIENT_REVERSAL_RECV_REQ_ITEM_BY_GET_ITEM_ID_OFFSET1			UPDATES_MMOCLIENT_REVERSAL_RECV_REQ_ITEM_BY_GET_ITEM_ID_OFFSET1  
#define MMOCLIENT_REVERSAL_RECV_REQ_ITEM_BY_GET_ITEM_ID_OFFSET2			UPDATES_MMOCLIENT_REVERSAL_RECV_REQ_ITEM_BY_GET_ITEM_ID_OFFSET2  
#define MMOCLIENT_REVERSAL_RECV_REQ_ITEM_BY_GET_ITEM_ID_OFFSET3___		0x8
#define MMOCLIENT_REVERSAL_RECV_REQ_ITEM_BY_GET_ITEM_COUNT_OFFSET___	0x3C
#define MMOCLIENT_REVERSAL_RECV_REQ_ITEM_BY_GET_ITEM_ID_CALL			UPDATES_MMOCLIENT_REVERSAL_RECV_REQ_ITEM_BY_GET_ITEM_ID_CALL  

// 攻击部位
#define MMOCLIENT_REVERSAL_HIT_PARAMETER_CALL_HOOK					UPDATES_MMOCLIENT_REVERSAL_HIT_PARAMETER_CALL_HOOK  		// 修改攻击部位的地址，也可用作无敌使用

#define MMOCLIENT_REVERSAL_HIT_BU_WEI_ID_PARAMETER_OFFSET___		0x4C
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_DIR_X_PARAMETER_OFFSET___		0xC4
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_DIR_Y_PARAMETER_OFFSET___		0xC8
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_X_PARAMETER_OFFSET___			0xCC
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_Y_PARAMETER_OFFSET___			0xD0
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_Z_PARAMETER_OFFSET___			0xD4

#define MMOCLIENT_REVERSAL_HIT_BU_WEI_X_PARAMETER_OFFSET2___			0x00
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_Y_PARAMETER_OFFSET2___			0x04
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_Z_PARAMETER_OFFSET2___			0x08
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_X_PARAMETER_OFFSET3___			0x0C
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_Y_PARAMETER_OFFSET3___			0x10
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_Z_PARAMETER_OFFSET3___			0x14
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_X_PARAMETER_OFFSET4___			0x64
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_Y_PARAMETER_OFFSET4___			0x68
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_Z_PARAMETER_OFFSET4___			0x6C

// 获取攻击部位结构体的数据hook地址
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_HOOK						UPDATES_MMOCLIENT_REVERSAL_HIT_BU_WEI_HOOK  	//    8B91 C8000000   MOV EDX,DWORD PTR DS:[ECX+0xC8]
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_ACOTR_ADDR2_OFFSET___		0x1C		// 对象addr2的偏移
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_STRUCT_ADDR_OFFSET___		0xC4		// 对象部位结构体偏移
#define MMOCLIENT_REVERSAL_HIT_BU_WEI_STRUCT_COUNT_OFFSET___	0xC8		// 对象部位的数量

// 通过 MMO_ActorVector 计算到对象的面向函数代码的基址
#define MMOCLIENT_REVERSAL_HIT_DIR_CALC_CALL_BASE_ADDR1		UPDATES_MMOCLIENT_REVERSAL_HIT_DIR_CALC_CALL_BASE_ADDR1  
#define MMOCLIENT_REVERSAL_HIT_DIR_CALC_CALL_BASE_ADDR2		UPDATES_MMOCLIENT_REVERSAL_HIT_DIR_CALC_CALL_BASE_ADDR2  

// 调和制作物品
#define MMOCLIENT_REVERSAL_GET_MANU_FACTURE_INFO_ADDR_CALL			UPDATES_MMOCLIENT_REVERSAL_GET_MANU_FACTURE_INFO_ADDR_CALL  
#define MMOCLIENT_REVERSAL_MANU_FACTURE_INFO_ID_OFFSET___			0x10	
#define MMOCLIENT_REVERSAL_MANU_FACTURE_INFO_NAME_OFFSET___			0x14
#define MMOCLIENT_REVERSAL_MANU_FACTURE_INFO_ITEM_ID_OFFSET___		0x58
#define MMOCLIENT_REVERSAL_MANU_FACTURE_INFO_MAIERSAL_OFFSET___		0x84

// Dialog弹框和遍历
#define MMOCLIENT_REVERSAL_GET_DIALOG_INFO_BASE_ADDR_CALL		UPDATES_MMOCLIENT_REVERSAL_GET_DIALOG_INFO_BASE_ADDR_CALL  
#define MMOCLIENT_REVERSAL_GET_DIALOG_INFO_DESC_OFFSET___		0x20
#define MMOCLIENT_REVERSAL_DIALOG_HOOK							UPDATES_MMOCLIENT_REVERSAL_DIALOG_HOOK   

// 获取农场种子信息
#define MMOCLIENT_REVERSAL_FARM_SEED_CALL						UPDATES_MMOCLIENT_REVERSAL_FARM_SEED_CALL  
#define MMOCLIENT_REVERSAL_FARM_SEED_NAME_OFFSET___	0x14

// 获取农村采集点信息
#define MMOCLIENT_REVERSAL_FARM_FACILITY_INFO_CALL				UPDATES_MMOCLIENT_REVERSAL_FARM_FACILITY_INFO_CALL  
#define MMOCLIENT_REVERSAL_FARM_FACILITY_INFO_ID_OFFSET___		0x10
#define MMOCLIENT_REVERSAL_FARM_FACILITY_INFO_LEVEL_OFFSET___	0x14
#define MMOCLIENT_REVERSAL_FARM_FACILITY_INFO_POINT_OFFSET___	0x20
#define MMOCLIENT_REVERSAL_FARM_FACILITY_INFO_YING_OFFSET___	0x24	
#define MMOCLIENT_REVERSAL_FARM_FACILITY_INFO_NAME_OFFSET___	0x50
#define MMOCLIENT_REVERSAL_FARM_FACILITY_INFO_DESC_OFFSET___	0x54
#define MMOCLIENT_REVERSAL_FARM_FACILITY_INFO_ROLE_LEVEL_OFFSET___	0x58


// #define MMOCLIENT_REVERSAL_CUR_FARM_FACILITY_LEVEL_OFFSET1___		0xD0
// #define MMOCLIENT_REVERSAL_CUR_FARM_FACILITY_LEVEL_OFFSET2___		0x8
#define MMOCLIENT_REVERSAL_CUR_FARM_FACILITY_LEVEL_OFFSET3___		0x28

#define MMOCLIENT_REVERSAL_FARM_CP_INFO_CALL				UPDATES_MMOCLIENT_REVERSAL_FARM_CP_INFO_CALL  
#define MMOCLIENT_REVERSAL_CUR_FARM_CP_TIME_OFFSET1___		0x1C		// 植物需要的成熟时间

#define MMOCLIENT_REVERSAL_GET_FARM_FACILITY_ID_CALL		UPDATES_MMOCLIENT_REVERSAL_GET_FARM_FACILITY_ID_CALL  	// 获取当前采集点的对象id

// 草药田的偏移
#define MMOCLIENT_REVERSAL_FARM_FACILITY_STATE_OFFSET1		UPDATES_MMOCLIENT_REVERSAL_FARM_FACILITY_STATE_OFFSET1  
#define MMOCLIENT_REVERSAL_FARM_FACILITY_STATE_OFFSET2		UPDATES_MMOCLIENT_REVERSAL_FARM_FACILITY_STATE_OFFSET2  
// 草药房的剩余时间计算函数
#define MMOCLIENT_REVERSAL_FARM_FACILITY_STATE_TIME_CALL	UPDATES_MMOCLIENT_REVERSAL_FARM_FACILITY_STATE_TIME_CALL  

// 获取出售物品价钱的call
#define MMOCLIENT_REVERSAL_GET_SELL_ITEM_PRICE_CALL			UPDATES_MMOCLIENT_REVERSAL_GET_SELL_ITEM_PRICE_CALL  

// 遍历补给箱
#define MMOCLIENT_REVERSAL_REQUIRE_SLOT_OFFSET1___		0xC
#define MMOCLIENT_REVERSAL_REQUIRE_SLOT_OFFSET2___		0x8C
#define MMOCLIENT_REVERSAL_REQUIRE_SLOT_OFFSET3___		0x18
#define MMOCLIENT_REVERSAL_REQUIRE_SLOT_OFFSET4___		0x4
#define MMOCLIENT_REVERSAL_REQUIRE_SLOT_OFFSET5___		0x18
#define MMOCLIENT_REVERSAL_REQUIRE_SLOT_OFFSET6___		0x10+8

// 遍历buffInfo
#define MMOCLIENT_REVERSAL_GET_BUFF_INFO_ADDR_CALL			UPDATES_MMOCLIENT_REVERSAL_GET_BUFF_INFO_ADDR_CALL  
#define MMOCLIENT_REVERSAL_ROLE_BUFF_STATE_ADDR_OFFSET___	0x10
#define MMOCLIENT_REVERSAL_ROLE_BUFF_STATE_OFFSET1			UPDATES_MMOCLIENT_REVERSAL_ROLE_BUFF_STATE_OFFSET1  	//0x18
#define MMOCLIENT_REVERSAL_ROLE_BUFF_STATE_OFFSET2___		0x1C
#define MMOCLIENT_REVERSAL_TIAN_QI_BUFF_STATE_OFFSET___		0x04
#define MMOCLIENT_REVERSAL_ROLE_BUFF_STATE_OFFSET3___		0x14
#define MMOCLIENT_REVERSAL_ROLE_BUFF_ACTOR_PACKET_ID_OFFSET___		0x4
#define MMOCLIENT_REVERSAL_ROLE_BUFF_FLAG_OFFSET___			0x18+4
#define MMOCLIENT_REVERSAL_ROLE_BUFF_INFO_ADDR_OFFSET___	0x34+4
#define MMOCLIENT_REVERSAL_BUFF_INFO_ID_OFFSET___			0x10
#define MMOCLIENT_REVERSAL_BUFF_INFO_NAME_OFFSET___			0x28
#define MMOCLIENT_REVERSAL_BUFF_INFO_DESC_OFFSET___			0x3A8//0x18C

// 领取礼包
#define MMOCLIENT_REVERSAL_GIFT_BAG_INFO_OFFSET1		UPDATES_MMOCLIENT_REVERSAL_GIFT_BAG_INFO_OFFSET1  
#define MMOCLIENT_REVERSAL_GIFT_BAG_INFO_OFFSET2___		0x10
#define MMOCLIENT_REVERSAL_GIFT_BAG_INFO_OFFSET3___		0x4
#define MMOCLIENT_REVERSAL_GIFT_BAG_GET_FLAG_OFFSET___		0x0C
#define MMOCLIENT_REVERSAL_GIFT_BAG_INFO_NAME_OFFSET___		0x8
#define MMOCLIENT_REVERSAL_GIFT_BAG_INFO_DESC_OFFSET___		0xC

// 获取等级经验信息的函数地址
#define MMOCLIENT_REVERSAL_PLAYER_LEVEL_UP_INFO_CALL		UPDATES_MMOCLIENT_REVERSAL_PLAYER_LEVEL_UP_INFO_CALL        
#define MMOCLIENT_REVERSAL_PLAYER_LEVEL_UP_INFO_MAX_EXP_OFFSET___	0x14

// 空中使用技能修改地址

#define MMOCLIENT_REVERSAL_KONG_ZHONG_USE_SKILL_JMP_ADDR		UPDATES_MMOCLIENT_REVERSAL_KONG_ZHONG_USE_SKILL_JMP_ADDR

// hook增加buff的代码段，增加奥妙之义
#define MMOCLIENT_REVERSAL_ADD_BUFFER_HOOK		UPDATES_MMOCLIENT_REVERSAL_ADD_BUFFER_HOOK  

// hook 输出信息
#define MMOCLIENT_REVERSAL_COUNT_DOWN_HOOK		UPDATES_MMOCLIENT_REVERSAL_COUNT_DOWN_HOOK  

// 周狩猎券可领取数量
#define MMOCLIENT_REVERSAL_WEEK_CREDIT_COUNT_OFFSET1		UPDATES_MMOCLIENT_REVERSAL_WEEK_CREDIT_COUNT_OFFSET1  
#define MMOCLIENT_REVERSAL_WEEK_CREDIT_COUNT_OFFSET2___		0xB4

#define MMOCLIENT_REVERSAL_WEEK_CREDIT_INFO_CALL			UPDATES_MMOCLIENT_REVERSAL_WEEK_CREDIT_INFO_CALL  

#define MMOCLIENT_REVERSAL_WEEK_CREDIT_COUNT_OFFSET___		0x14
#define MMOCLIENT_REVERSAL_WEEK_CREDIT_COUNT_CALL			UPDATES_MMOCLIENT_REVERSAL_WEEK_CREDIT_COUNT_CALL  

#define MMOCLIENT_REVERSAL_WEEK_CREDIT_HAS_RECEIVE_COUNT_OFFSET___		0x38		// 已领取的周狩猎券

// hook 获取当前角色地面的z坐标
#define MMOCLIENT_REVERSAL_MAP_COORDINATES_HOOK___		0x0CB60DE8-0x0C370000

/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

******************************分割线**************************************

--------------------------------------------------------------------------------*/

//////////////////////////////////////////////////////////////////////////
// 组包部分

#define MMOCLIENT_REVERSAL_PACKET_HEADER_VALUE_OFFSET___	0x10		// 封包数据的起始处
#define MMOCLIENT_REVERSAL_PACKET_BUF_SIZE___				0xE6

#define MMOCLIENT_REVERSAL_PACKET_RECV_MSG_MY_REQ_COUNT_OFFSET___	0x8			// 查询我的拍卖列表返回数据的拍卖物品数量
#define MMOCLIENT_REVERSAL_PACKET_RECV_MSG_MY_REQ_DATA_OFFSET___	0x0A		// 查询我的拍卖列表返回数据的拍卖物品的起始偏移

#define MMOCLIENT_REVERSAL_ROLE_HP_STATE_RET_PACKET_FALG___		0x2B		// 508封包细分类型 角色中毒状态，过图状态，被电状态
#define MMOCLIENT_REVERSAL_ROLE_HP_STATE_ZHONG_DU_STATE___		0x7049		// 中毒后的状态包，这个数据是从分析的时候获取的，其实是字符串的“Ip”
//////////////////////////////////////////////////////////////////////////
//********************消息ID**********************************************
// 发包
#define MMOCLIENT_REVERSAL_PACKET_SAY_METHOD___				0x101			// 封包类型 word类型 喊话
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_WALK___			0x00000286		// walk，移动
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_HIT___				0x000002C1		// 攻击封包
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_ACCEPT_TASK___		0xE01			// 接任务
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_COMPLETE_TASK___	0xE04			// 交任务
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_GUO_TU___			0x0000025B		// 副本过图
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_CITY_GUO_TU___		0x00000042		// 城镇过图
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_OPEN_NPC___		0x00001401		// 打开NPC
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_MOVE_TO___			0x000003004		// 移动物品到
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_MOVE_COUNT_TO___	0x000003008		// 移动指定数量物品到 已存在的物品里
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_MOVE_COUNT_TO_EMPTY___	0x00000300A		// 移动指定数量物品到 空格里
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_GET_ITEM___		0x00000D01		// 补给箱取物品
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_FACTURE___			0x00001001		// 调和制作 
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_GET_MAIL_ITEM___	0x00001B07		// 获取邮件物品
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_OPEN_MAIL___		0x00001B03		// 打开邮箱
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_DELETE_MAIL___		0x00001B29		// 删除邮件
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_TASK_NPC_CHAT___	0x00002402		// 和NPC交谈
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_GOTO_FB1___		0x19			// 进入副本封包1 
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_GOTO_FB2___		0x21			// 进入副本封包2 
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_GOTO_FB3___		0x23			// 进入副本封包3 
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_SELL_ITEM___		0x00000F03		// 出售物品
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_BUY_REQ_ITEM___	0x00001505		// 封包购买拍卖物品
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_SHANG_JIA_AUCTION_ITEM___		0x00001501		// 上架拍卖物品
#define MMOCLIENT_SOCIATY_TASK_MSG_ID							0x00000035	//公会任务消息ID
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_REQ_ITEM_BY_TYPE___	0x00001507	// 查询拍卖物品
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_UP_EQUIP___			0x0000310D	// 升级装备
#define MMOCLIENT_REVERSAL_XIN_SHOU_XUN_LIAN_LI_KAI_JIAO_XUE___	0x000000A2	// 新手训练—离开教学副本  和进入教学副本是同一个封包，但为了区分，这里存在两个相同的发包ID
#define MMOCLIENT_REVERSAL_JIN_RU_JIAO_XUE_FB___				0x000000A2	// 进入教学副本
#define MMOCLIENT_REVERSAL_GET_WEEK_CREDIT_COUNT___				0x00002801	// 获取狩猎券
#define MMOCLIENT_REVERSAL_PACKET_SYN_COOR_DINATES___			0x00000292	// 同步坐标封包

// 收包
#define MMOCLIENT_REVERSAL_ACCEPT_TASK_MSG_ID___			0x0E51			// 接受任务	
#define MMOCLIENT_REVERSAL_GIVE_UP_TASK_MSG_ID___			0x0E52			// 放弃任务 
#define MMOCLIENT_REVERSAL_ACCEPT_MAIL_VALUE_RET_MSG_ID___	0x00001B08		// 操作邮件的返回值
#define MMOCLIENT_REVERSAL_PACKET_MSG_MOSTER_SIWANG___		0x283			// 对象死亡封包
#define MMOCLIENT_REVERSAL_PACKET_RECV_MSG_PLAYER_LIST___	0x02			// 玩家列表
#define MMOCLIENT_REVERSAL_PACKET_RECV_MSG_LINE___			0x00000054		// 选择玩家后，选择路线的遍历
#define MMOCLIENT_REVERSAL_PACKET_RECV_MSG_CREATE_ROLE_RET___	0x00000004	// 创建角色返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_MSG_IN_FB_RET___			0x22		// 选择副本和确认进入副本的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_REQ_ITEM_BY_TYPE___		0x00001509	// 查询拍卖的返回数据
#define MMOCLIENT_REVERSAL_PACKET_RECV_REQ_ITEM_BY_TYPE_MY___	0x00001512	// 查询我的拍卖出售的返回数据
#define MMOCLIENT_REVERSAL_PACKET_RECV_INVITE_TEAM_FAIL___		0x00000726	// 邀请组队的返回值 ==》 组队失败：xx拒绝了你的组队邀请
#define MMOCLIENT_REVERSAL_PACKET_RECV_TEAM_INFO___				0x00000706	// 在角色不是队长的情况下申请组队和创建队伍返回值  ==》 第一次获取队伍信息会有此返回包
#define MMOCLIENT_REVERSAL_PACKET_RECV_JOIN_TEAM_INFO___		0x0000070B	// 在角色为队长的情况下，有新加入的队员返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_LEAVE_TEAM___			0x0000070E	// 有队员离开队伍
#define MMOCLIENT_REVERSAL_PACKET_RECV_BE_LEAVE_TEAM___			0x00000711	// 有成员被请离队伍
#define MMOCLIENT_REVERSAL_PACKET_RECV_DISS_TEAM___				0x0000070D	// 队长退出队伍
#define MMOCLIENT_REVERSAL_PACKET_RECV_TEAM_ERROR___			0x00000725	// 组队的错误码
#define MMOCLIENT_REVERSAL_PACKET_RECV_TASK_FB_INFO___			0x0000003E	// 公会任务副本，千狩副本，喵喵副本的返回值
#define MMOCLIENT_REVERSAL_AN_QUAN_BAO_HU_TIME___				0x00001904	// 安全保护时间
#define MMOCLIENT_REVERSAL_PACKET_RECV_REQ_BUY_ITEM_RET___		0x00001506	// 购买拍卖物品的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_JI_YUN_FB_RET___			0x00004202	// 获取激运副本的信息
#define MMOCLIENT_REVERSAL_PACKET_RECV_OPEN_NPC_RET___			0x00001402	// 打开npc返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_SHANG_JIA_ITEM_RET___	0x00001502	// 上架拍卖物品的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_SELL_ITEM_RET___			0x00000F04	// 出售物品的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_COMPLETE_TASK_RET___		0x00000E53	// 提交任务成功的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_COMPLETE_TASK_FAIL_RET___	0x00000E55	// 提交任务失败的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_NPC_CHAT_RET___			0x00000E57	// 交谈任务npc返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_FRAM_SEED_RET___			0x000002FC	// 种植种子的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_FEEB_HP_RET___			0x00000405	// 持续减血的返回包
#define MMOCLIENT_REVERSAL_PACKET_RECV_SEND_MAIL_RET___			0x00001B0A	// 发送邮件的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_ROLE_HP_STATE_RET___		0x00000508	// 所有对象的返回状态包
#define MMOCLIENT_REVERSAL_PACKET_RECV_USE_ITEM_RET___			0x00003002	// 使用物品的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_USE_ITEM_RET2___			0x00003003	// 使用物品后没有剩余物品的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_BUY_ITEM_RET___			0x00000F02	// 购买物品的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_GET_GFIT_BAG_RET___		0x00002602	// 领取礼包
#define MMOCLIENT_REVERSAL_PACKET_RECV_COLLECT_ITEM_BAG_FULL_RET___		0x00000C02	// 采集物品背包已满的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_TIDY_INVENTORY_ITEM_RET___		0x0000300C	// 整理背包或仓库的返回值
#define MMOCLIENT_REVERSAL_PACKET_RECV_SEND_MAIL_RET2___		0x00001B2D		// 发送邮件频繁的返回值
//////////////////////////////////////////////////////////////////////////		
// 接受任务的参数类型
#define MMOCLIENT_REVERSAL_ACCEPT_TASK_TYPE_PU_TONG___		0x01		// 正常接受的普通任务
#define MMOCLIENT_REVERSAL_ACCEPT_TASK_TYPE_GONG_HUI___		0x02		// 接受公会的任务
#define MMOCLIENT_REVERSAL_ACCEPT_TASK_TYPE_QIAN_SHOU___	0x02		// 千狩副本的任务

//////////////////////////////////////////////////////////////////////////
// 公会任务的等级 ==> 废弃
#define MMOCLIENT_REVERSAL_ACCEPT_GONG_HUI_FB_LEVEL1___		0x64		// 委托★
#define MMOCLIENT_REVERSAL_ACCEPT_GONG_HUI_FB_LEVEL2___		0x65		// 委托★★
#define MMOCLIENT_REVERSAL_ACCEPT_GONG_HUI_FB_LEVEL3___		0x66		// 委托★★★
#define MMOCLIENT_REVERSAL_ACCEPT_GONG_HUI_FB_LEVEL4___		0x67		// 委托★★★★
#define MMOCLIENT_REVERSAL_ACCEPT_GONG_HUI_FB_LEVEL5___		0x67		// 委托★★★★★
#define MMOCLIENT_REVERSAL_ACCEPT_GONG_HUI_FB_LEVEL6___		0x67		// 委托★★★★★★

// 副本任务
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_GONG_HUI_INDEX___		1		// 公会副本
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_MIAO_MIAO_INDEX___		3		// 喵喵副本
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_QIAN_SHOU_INDEX___		4		// 千狩副本

#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_GONG_HUI_KEY___		0x0000985E		// 公会副本
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_MIAO_MIAO_KEY___		0x000075C2		// 喵喵副本
#define MMOCLIENT_REVERSAL_PACKET_MSG_ID_QIAN_SHOU_KEY___		0x000075B6		// 千狩副本
//////////////////////////////////////////////////////////////////////////
//********************消息结构中某些字段的偏移**********************************************
#define MMOCLIENT_REVERSAL_PACKET_MSG_MOSTER_SIWANG_PACKET_ID 0x18
#define MMOCLIENT_REVERSAL_RECV_PLAYER_LIST_COUNT___		0x18+4
#define MMOCLIENT_REVERSAL_RECV_PLAYER_INFO_OFFSET___		0x1A+4
#define MMOCLIENT_REVERSAL_RECV_PACKET_DATA_OFFSET___		0x10 		//	封包内容偏移
//////////////////////////////////////////////////////////////////////////
// 技能id
#define MMOCLIENT_REVERSAL_SKILL_ID_MOUSE_LEFT		0		// 鼠标左键
#define MMOCLIENT_REVERSAL_SKILL_ID_MOUSE_RIGHT		1		// 鼠标右键
#define MMOCLIENT_REVERSAL_SKILL_ID_KEYBOARD_Q		3		// 键盘q，收刀
#define MMOCLIENT_REVERSAL_SKILL_ID_KEYBOARD_Z		4		// 键盘z，采集，扒皮
#define MMOCLIENT_REVERSAL_SKILL_ID_KEYBOARD_E		5		// 键盘e，刺
#define MMOCLIENT_REVERSAL_SKILL_ID_KEYBOARD_F		0x0C	// 键盘f，奥义觉醒

// buffid
#define MMOCLIENT_REVERSAL_SKILL_BUFF_ID_F			0x04C4B416	// 奥义觉醒
//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////
// NPC的类型区分
#define MMOCLIENT_REVERSAL_NPC_TYPE_BOSS			1		// BOSS
#define MMOCLIENT_REVERSAL_NPC_TYPE_XIAO_GUAI		2		// 小怪
#define MMOCLIENT_REVERSAL_NPC_TYPE_BU_JI_XIANG		3
//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////
// 任务类型
#define MMOCLIENT_REVERSAL_TASK_ZHU_XIAN			0x01
#define MMOCLIENT_REVERSAL_TASK_ZHI_XIAN			0x02
#define MMOCLIENT_REVERSAL_TASK_RI_CHANG			0x20
#define MMOCLIENT_REVERSAL_TASK_GONG_HUI			0x40
#define MMOCLIENT_REVERSAL_TASK_SHANG_JIN			0x400
// 其他未知类型
//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////
// class
#define MMOCLIENT_REVERSAL_TRAVERSE_ACTOR_TYPE_PLAY1___		0x0597
#define MMOCLIENT_REVERSAL_TRAVERSE_ACTOR_TYPE_PLAY2___		0x05B0
#define MMOCLIENT_REVERSAL_TRAVERSE_ACTOR_TYPE_STATIC___	0x04B0
#define MMOCLIENT_REVERSAL_TRAVERSE_ACTOR_TYPE_NPC___		0x0497
#define MMOCLIENT_REVERSAL_TRAVERSE_ACTOR_TYPE_COLLECT___	0x0695
#define MMOCLIENT_REVERSAL_TRAVERSE_ACTOR_TYPE_DOOR___		0x0690
#define MMOCLIENT_REVERSAL_TRAVERSE_ACTOR_TYPE_DOOR2___		0x0790
#define MMOCLIENT_REVERSAL_TRAVERSE_ACTOR_TYPE_APEAR___		0x00000510		// 比如闪光的东西
#define MMOCLIENT_REVERSAL_TRAVERSE_ACTOR_TYPE_ROCK___		0x00000595		// 石块 副本任务 莉莉的风格
//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////
// 城镇to城镇的字符串
#define MMOCLIENT_REVERSAL_XI_MEI_LUN_SHAN_LU_TO_LONG_ZHI_HU			"Hub1ToHub2Triigger"		// 希美伦山路 	==> 龙趾湖	Hub1ToHub2Triigger
#define MMOCLIENT_REVERSAL_LONG_ZHI_HU_TO_XI_MEI_LUN_SHAN_LU			"Teleporter_To_Hub001"		// 龙趾湖		==> 希美伦山路	Teleporter_To_Hub001

#define MMOCLIENT_REVERSAL_XI_MEI_LUN_SHAN_LU_TO_MI_DE_LA_CUN			"HubToVillageTrigger"		// 希美伦山路 	==> 米拉德村	HubToVillageTrigger
#define MMOCLIENT_REVERSAL_MI_DE_LA_CUN_TO_XI_MEI_LUN_SHAN_LU			"VillageToHubTrigger"		// 米拉德村		==> 希美伦山路	VillageToHubTrigger

#define MMOCLIENT_REVERSAL_LONG_ZHI_HU_TO_MEI_JIE_BO_ER_TAN				"Teleporter_To_Village02"	// 龙趾湖		==> 梅杰波尔坦	Teleporter_To_Village02
#define MMOCLIENT_REVERSAL_MEI_JIE_BO_ER_TAN_TO_LONG_ZHI_HU				"Village2_To_Hub2_Trigger"	// 梅杰波尔坦	==> 龙趾湖	Village2_To_Hub2_Trigger

#define MMOCLIENT_REVERSAL_MEI_JIE_BO_ER_TAN_TO_YAO_YUE_LIN				"Village2_To_Hub3_Trigger"	// 梅杰波尔坦	==> 耀月林	Village2_To_Hub3_Trigger
#define MMOCLIENT_REVERSAL_YAO_YUE_LIN_TO_MEI_JIE_BO_ER_TAN				"TeleporterToVillage02"		// 耀月林		==> 梅杰波尔坦	TeleporterToVillage02


//////////////////////////////////////////////////////////////////////////
//shop id info
#define MMOCLIENT_SHOP_INFO_LIE_SHOU_BU_JI_PIN				2			// 猎守补给品
#define MMOCLIENT_SHOP_INFO_AI_LU_NONG_YE_TE_GONG			0x06		// 艾露农业特供
#define MMOCLIENT_SHOP_INFO_ZHUANG_YUAN_BI_XU_PIN			0x09		// 庄园必须品
#define MMOCLIENT_SHOP_INFO_AI_LU_MAO_GU_YONG				5			// 艾路猫雇佣
#define MMOCLIENT_SHOP_INFO_XIN_SHOU_LIE_SHOU_EQUIP			7			// 新手猎守装备
#define MMOCLIENT_SHOP_INFO_DAN_YAO_BU_JI					0x0F		// 弹药补给
#define MMOCLIENT_SHOP_INFO_GONG_JIAN_PING_TE_MAI			0x10		// 弓箭瓶特卖
#define MMOCLIENT_SHOP_INFO_RU_MEN_XU_KE					0x22		// 教官-猎守武器入门许可
#define MMOCLIENT_SHOP_INFO_EQUIP_SKILL						0x23		// 教官-武器技能
#define MMOCLIENT_SHOP_INFO_LI_WEI							0x26		// 神秘的商人-莉薇
//////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////
// 其他
#define MMOCLIENT_SOCIATY_TASK_UNKNOWN_DATA					0x985e		//公会任务未知数据
#define MMOCLIENT_SOCIATY_TASK_FLAG							1			//公会任务标志

//////////////////////////////////////////////////////////////////////////
// dx按键
/*
 * VK_0 - VK_9 are the same as ASCII '0' - '9' (0x30 - 0x39)
 * 0x40 : unassigned
 * VK_A - VK_Z are the same as ASCII 'A' - 'Z' (0x41 - 0x5A)
 */
/* VK_0 thru VK_9 are the same as ASCII '0' thru '9' (0x30 - 0x39) */
#define VK_0 0x30
#define VK_1 0x31
#define VK_2 0x32
#define VK_3 0x33
#define VK_4 0x34
#define VK_5 0x35
#define VK_6 0x36
#define VK_7 0x37
#define VK_8 0x38
#define VK_9 0x39
/* VK_A thru VK_Z are the same as ASCII 'A' thru 'Z' (0x41 - 0x5A) */
#define VK_A 0x41
#define VK_B 0x42
#define VK_C 0x43
#define VK_D 0x44
#define VK_E 0x45
#define VK_F 0x46
#define VK_G 0x47
#define VK_H 0x48
#define VK_I 0x49
#define VK_J 0x4A
#define VK_K 0x4B
#define VK_L 0x4C
#define VK_M 0x4D
#define VK_N 0x4E
#define VK_O 0x4F
#define VK_P 0x50
#define VK_Q 0x51
#define VK_R 0x52
#define VK_S 0x53
#define VK_T 0x54
#define VK_U 0x55
#define VK_V 0x56
#define VK_W 0x57
#define VK_X 0x58
#define VK_Y 0x59
#define VK_Z 0x5A

#define VK_126  126