#pragma once
#define UPDATES_FIFA_REVERSAL_HTTP_SEND_CALL  0X00D4A8B0
#define UPDATES_FIFA_REVERSAL_SSL_READ_AND_WRITE_SOCKET_ADDR_HOOK  0X00D51EA7
#define UPDATES_FIFA_REVERSAL_SSL_WRITE  0X00434700
#define UPDATES_FIFA_REVERSAL_SSL_READ  0X00434660
#define UPDATES_FIFA_REVERSAL_SSL_GET_ERROR  0X00436200
#define UPDATES_FIFA_REVERSAL_HOOK_RECV_CALL_ADDR_ZHP  0X00D51CBF
#define UPDATES_FIFA_REVERSAL_HOOK_ANIMATION_FEATURE  0X0093CE90
#define UPDATES_FIFA_REVERSAL_HOOK_TOP_COMMAND_FN  0X0093CEF0
#define UPDATES_FIFA_REVERSAL_HOOK_AFTER_GET_DEVICE_STATE  0X00B68A46
#define UPDATES_FIFA_REVERSAL_HOOK_DX_INPUT_MODEL  0X00B671DA
#define UPDATES_FIFA_REVERSAL_HOOK_FOR_GAIN_MAIN_WND_HANDLE  0X00BAEA88
#define UPDATES_FIFA_REVERSAL_MEMOPER_G_CALLOC  0X017BD250
#define UPDATES_FIFA_REVERSAL_MEMOPER_G_MALLOC  0X017BD240
#define UPDATES_FIFA_REVERSAL_MEMOPER_G_FREE  0X017BD244
#define UPDATES_FIFA_REVERSAL_MEMOPER_GET_MOUSE_KEY_EVENT_HANDLER  0X0095B440
#define UPDATES_FIFA_REVERSAL_HOOK_AFTER_GAME_READ_FULL_HTTP_PACKAGE  0X00D4714D
#define UPDATES_FIFA_REVERSAL_FIFAZFBASE_SPRINTF_ADDR  0X0012F695
#define UPDATES_FIFA_REVERSAL_STOP_RENDER_AND_SLEEP_HOOK  0X005EBDC0
/**************************************特征码更新结束*******************************************/