del /q "F:\proj\cpp\subs\PathOfExile\Debug\gl.pdb"
del /q "F:\proj\cpp\subs\PathOfExile\gj_d\gl.pdb"
del /q "F:\proj\cpp\subs\PathOfExile\gj3_d\gl.pdb"
del /q "F:\proj\cpp\subs\PathOfExile\CrackData\Debug\AutoUpdate.pdb"
del /q "F:\proj\cpp\subs\PathOfExile\CrackData\gj_d\AutoUpdate.pdb"
del /q "F:\proj\cpp\subs\PathOfExile\CrackData\gj3_d\AutoUpdate.pdb"
del /q "F:\proj\cpp\subs\PathOfExile\Data\Debug\PluginTest.pdb"
del /q "F:\proj\cpp\subs\PathOfExile\Data\gj_d\PluginTest.pdb"
del /q "F:\proj\cpp\subs\PathOfExile\Data\gj3_d\PluginTest.pdb"
pause