//////////////////////////////////////////////////////////////////////////////////////
// jfzrbase.h
// 文件功能: 团队内部统一更新地址宏
// 第一部分：基址和偏移部分
// 第二部分：封包所用到的固定数据和字符串
// 备注: 凡是以 "___" 结尾表示没有特征码，更新时需要注意查看
// 提示: 凡事更新了特征码的宏，都会去掉宏末尾的三条“_”
//////////////////////////////////////////////////////////////////////////////////////

#include "updates.h"

//////////////////////////////////////////////////////////////////////////////////////
// 第一部分：基址和偏移部分
//////////////////////////////////////////////////////////////////////////////////////

// 基址 暂时用于发包CALL的SOCKET
#define JFZR_REVERSAL_SEND_PACKET_SOCKET_ADDR			UPDATES_JFZR_REVERSAL_SEND_PACKET_SOCKET_ADDR    
#define JFZR_REVERSAL_SEND_PACKET_SOCKET_OFFSET___		0x0

// 通过HOOK此处获取发包CALL的加密对象，任务对象的对象地址
#define JFZR_REVERSAL_SEND_ARGC3_ARGC4_HOOK_ADDR		UPDATES_JFZR_REVERSAL_SEND_ARGC3_ARGC4_HOOK_ADDR			// hook改变，从原来的ecx改为取esi

// 通过获取到发包对象地址 和 发包CALL所用参数3,4 相减获取
#define JFZR_REVERSAL_SEND_PACKET_OFFSET				0

#define JFZR_REVERSAL_SEND_PACKET_JIAMI_OBJ_OFFSET		UPDATES_JFZR_REVERSAL_SEND_PACKET_JIAMI_OBJ_OFFSET
#define JFZR_REVERSAL_SEND_PACKET_TASK_OBJ_OFFSET		UPDATES_JFZR_REVERSAL_SEND_PACKET_TASK_OBJ_OFFSET

// 发包CALL压入两个参数 CALL，并置封包任务数量
#define	JFZR_REVERSAL_SEND_PUSH_ARGC3_ARGC4_CALL		UPDATES_JFZR_REVERSAL_SEND_PUSH_ARGC3_ARGC4_CALL 	
// 明文发包CALL
#define JFZR_REVERSAL_SEND_ADDR_CALL					UPDATES_JFZR_REVERSAL_SEND_ADDR_CALL  
#define JFZR_REVERSAL_SEND_ADDR_PRE_CALL_HOOK			UPDATES_JFZR_REVERSAL_SEND_ADDR_PRE_CALL_HOOK
// 发包CALL之前申请对象
#define JFZR_REVERSAL_SEND_ALLOC_OBJ_CALL				UPDATES_JFZR_REVERSAL_SEND_ALLOC_OBJ_CALL  
// 发包CALL之后释放对象
#define JFZR_REVERSAL_SEND_FREE_OBJ_CALL				UPDATES_JFZR_REVERSAL_SEND_FREE_OBJ_CALL  
// 游戏内部管理内存函数地址
#define JFZR_REVERSAL_ALLMMEMORY_ALLOC_ADDR				UPDATES_JFZR_REVERSAL_ALLMMEMORY_ALLOC_ADDR         
#define JFZR_REVERSAL_ALLMMEMORY_FREE_ADDR				UPDATES_JFZR_REVERSAL_ALLMMEMORY_FREE_ADDR         

// 游戏内部对memcpy实现了一层封装，注意：拷贝必须用这个，自己实现的无效
#define JFZR_REVERSAL_GAME_MEMCPY_CALL					UPDATES_JFZR_REVERSAL_GAME_MEMCPY_CALL        

// 走路命令CALL
#define JFZR_REVERSAL_ZOULU_CALL						UPDATES_JFZR_REVERSAL_ZOULU_CALL          


// hook 遍历局部怪物对象,可遍历到副本内的对象和城镇的对象
#define JFZR_REVERSAL_LOCAL_OBJ_ADDR_HOOK				UPDATES_JFZR_REVERSAL_LOCAL_OBJ_ADDR_HOOK       
#define JFZR_REVERSAL_LOCAL_OBJ_HOOK_OLD_CODE			0x55,0x8B,0xEC,0x6A,0xFF
#define JFZR_REVERSAL_LOCAL_OBJ_LIST_OFFSET				UPDATES_JFZR_REVERSAL_LOCAL_OBJ_LIST_OFFSET

#define JFZR_REVERSAL_LOCAL_OBJ_OFFSET1					UPDATES_JFZR_REVERSAL_LOCAL_OBJ_OFFSET1
#define JFZR_REVERSAL_LOCAL_OBJ_OFFSET2					UPDATES_JFZR_REVERSAL_LOCAL_OBJ_OFFSET2
#define JFZR_REVERSAL_LOCAL_OBJ_OFFSET3					UPDATES_JFZR_REVERSAL_LOCAL_OBJ_OFFSET3
#define JFZR_REVERSAL_LOCAL_OBJ_OFFSET4___				0x0
#define JFZR_REVERSAL_LOCAL_OBJ_SERIAL_OFFSET___		0x4
#define JFZR_REVERSAL_LOCAL_OBJ_JOBLEN_OFFSET___		0x1C
#define JFZR_REVERSAL_LOACL_OBJ_JOBNAME_OFFSET___		0x8
#define JFZR_REVERSAL_LOCAL_OBJ_NAMELEN_OFFSET___		0x38
#define JFZR_REVERSAL_LOACL_OBJ_NAME_OFFSET___			0x24
#define JRZR_REVERSAL_LOCAL_OBJ_TYPELEN_OFFSET___		0x144
#define JFZR_REVERSAL_LOCAL_OBJ_TPYE_OFFSET___			0x130
#define JFZR_REVERSAL_ACTOR_OBJ_LEVEL_OFFSET___			0x14C		// 遍历到的对象的等级
#define JFZR_REVERSAL_LOCAL_OBJ_X_OFFSET				UPDATES_JFZR_REVERSAL_LOCAL_OBJ_X_OFFSET
#define JFZR_REVERSAL_LOCAL_OBJ_Z_OFFSET				UPDATES_JFZR_REVERSAL_LOCAL_OBJ_Z_OFFSET
#define JFZR_REVERSAL_LOCAL_OBJ_Y_OFFSET				UPDATES_JFZR_REVERSAL_LOCAL_OBJ_Y_OFFSET
#define JFZR_REVERSAL_LOCAL_OBJ_DIRECTION_X_OFFSET___	0x80
#define JFZR_REVERSAL_LOCAL_OBJ_DIRECTION_Z_OFFSET___	0x84
#define JFZR_REVERSAL_LOCAL_OBJ_DIRECTION_Y_OFFSET___	0x88
#define JFZR_REVERSAL_LOCAL_OBJ_HP_OFFSET___			0xB60
#define JFZR_REVERSAL_LOCAL_OBJ_MAXHP_OFFSET___			0xB64
#define JFZR_REVERSAL_LOCAL_OBJ_MP_OFFSET___			0xB68
#define JFZR_REVERSAL_LOCAL_OBJ_MAXMP_OFFSET___			0xB6C
#define JFZR_REVERSAL_ACTOR_OBJ_IS_DEAD_OFFSET___		0xB70
#define JFZR_REVERSAL_ITEM_EXISTS_OFFSET___				0xB78		//ItemExists
#define JFZR_REVERSAL_LOCAL_OBJ_DEFAULT_ACTION_ID_OFFSET___		0x110

#define JFZR_REVERSAL_LOCAL_OBJ_NPC_TYPE_FLAG_1___		0x344
#define JFZR_REVERSAL_LOCAL_OBJ_NPC_TYPE_FLAG_2___		0x9D4

// 对象基址，用于技能，背包，装备等信息查询
#define JFZR_REVERSAL_ROLE_OBJ_ADDR						UPDATES_JFZR_REVERSAL_ROLE_OBJ_ADDR  

// 技能偏移
#define JFZR_REVERSAL_SKILL_OFFSET1						UPDATES_JFZR_REVERSAL_SKILL_OFFSET1
#define JFZR_REVERSAL_SKILL_OFFSET2						UPDATES_JFZR_REVERSAL_SKILL_OFFSET2
#define JFZR_REVERSAL_SKILL_OBJ_NAMELEN_OFFSET___		0x14	
#define JFZR_REVERSAL_SKILL_OBJ_NAME_OFFSET___			0x4
#define JFZR_REVERSAL_SKILL_OBJ_LEVEL_OFFSET___			0x20
#define JFZR_REVERSAL_SKILL_OBJ_ID_OFFSET___			0x44
#define JFZR_REVERSAL_SKILL_OBJ_SIZE___					0x48

// sp
#define JFZR_REVERSAL_SKILL_SP_OFFSET1___				0x70
#define JFZR_REVERSAL_SKILL_SP_OFFSET2___				0x4C
#define JFZR_REVERSAL_SKILL_SP_INDEX_OFFSET___			0x1DE	


// [JFZR_REVERSAL_ROLE_OBJ_ADDR+JFZR_REVERSAL_ROLE_GOLD_OFFSET1+JFZR_REVERSAL_ROLE_GOLE_OFFSET2] = 金币
#define JFZR_REVERSAL_ROLE_GOLD_OFFSET1					UPDATES_JFZR_REVERSAL_FB_OFFSET1	
#define JFZR_REVERSAL_ROLE_GOLE_OFFSET2					UPDATES_JFZR_REVERSAL_ROLE_GOLE_OFFSET2

// 人物基址
#define JFZR_REVERSAL_ROLE_BASE_ADDR					UPDATES_JFZR_REVERSAL_ROLE_BASE_ADDR  
#define JFZR_REVERSAL_ROLE_SERIAL_OFFSET___				0x4
#define JFZR_REVERSAL_ROLE_LEVEL_OFFSET					UPDATES_JFZR_REVERSAL_ROLE_LEVEL_OFFSET
#define JFZR_REVERSAL_ROLE_SKILL_RUN_SERIAL_ADDR		UPDATES_JFZR_REVERSAL_ROLE_SKILL_RUN_SERIAL_ADDR

// 获取随机种子
#define JFZR_REVERSAL_RANDOMSEED_CALL					UPDATES_JFZR_REVERSAL_RANDOMSEED_CALL              

// 获取当前角色所在房间对象 HOOK 点 包括：房间序号，门对象
#define JFZR_REVERSAL_LOCAL_ROOM_OBJ_HOOK				UPDATES_JFZR_REVERSAL_LOCAL_ROOM_OBJ_HOOK   
#define JFZR_REVERSAL_LOCAL_ROOM_MAP_OFFSET___			0x4
#define JFZR_REVERSAL_LOCAL_ROOM_MAP_LEN_OFFSET___		0x18
#define JFZR_REVERSAL_LOCAL_ROOM_ID_OFFSET___			0x24
#define JFZR_REVERSAL_LOCAL_ROOM_ID_LEN_OFFSET___		0x38
#define JFZR_REVERSAL_LOCAL_ROOM_DOOR_OBJ_OFFSET___		0x88
#define JFZR_REVERSAL_LOCAL_ROOM_WARP_NAME_OFFSET___	0x0C
#define JFZR_REVERSAL_LOCAL_ROOM_WARP_LEN_OFFSET___		0x20
#define JFZR_REVERSAL_LOCAL_ROOM_X_OFFSET___			0x48
#define JFZR_REVERSAL_LOCAL_ROOM_Y_OFFSET___			0x4C
#define JFZR_REVERSAL_LOCAL_ROOM_Z_OFFSET___			0x50

// 背包物品
#define JFZR_REVERSAL_ITEM_BAG_OFFSET1						UPDATES_JFZR_REVERSAL_RECEIVED_TASK_OBJ_OFFSET1
#define JFZR_REVERSAL_ITEM_BAG_OFFSET2						UPDATES_JFZR_REVERSAL_ITEM_BAG_OFFSET2
#define JFZR_REVERSAL_ITEM_BAG_OFFSET3						UPDATES_JFZR_REVERSAL_ITEM_BAG_OFFSET3
#define JFZR_REVERSAL_ITEM_BAG_OFFSET4						UPDATES_JFZR_REVERSAL_ITEM_BAG_OFFSET4

#define JFZR_REVERSAL_ITEM_OBJ_SIZE___						0x208

#define JFZR_REVERSAL_ITEM_BAG_NAME_LEN_OFFSET___			0x14
#define JFZR_REVERSAL_ITEM_BAG_NAME_OFSSET___				0x4
#define JFZR_REVERSAL_ITEM_BAG_QUALITY_NAME_LEN_OFFSET___	0x68
#define JFZR_REVERSAL_ITEM_BAG_COUNT_OFFSET___				0x50
#define JFZR_REVERSAL_ITEM_BAG_QUALITY_NAME_OFFSET___		0x54
#define JFZR_REVERSAL_ITEM_BAG_DURABLE_OFFSET___			0x70
#define JFZR_REVERSAL_ITEM_BAG_OBJ_OFFSET___				0x48
#define JFZR_REVERSAL_ITEM_BAG_SEAL_OFFSET___				0x0E8	// IsSealed
#define JFZR_REVERSAL_ITEM_BAG_IDENTIFICATION_OFFSET___		0x0E9	// IsUnidentified
#define JFZR_REVERSAL_ITEM_BAG_IS_TRADABLE_OFFSET___		0x0EA	// IsTradable

// 偏移未确定
#define JFZR_REVERSAL_ITEM_OBJ_USE_LEN_OFFSET___			0x138
#define JFZR_REVERSAL_ITEM_OBJ_USE_OFFSET___				0x124
#define JFZR_REVERSAL_ITEM_OBJ_TYPE_LEN_OFFSET___			0x194
#define JFZR_REVERSAL_ITEM_OBJ_TYPE_OFFSET___				0x180



// 装备
#define JFZR_REVERSAL_EQUIP_ITEM_OFFSET3					UPDATES_JFZR_REVERSAL_EQUIP_ITEM_OFFSET3
#define JFZR_REVERSAL_EQUIP_ITEM_OFFSET4					UPDATES_JFZR_REVERSAL_EQUIP_ITEM_OFFSET4

// 副本选择
#define JFZR_REVERSAL_FB_OFFSET1							UPDATES_JFZR_REVERSAL_FB_OFFSET1
#define JFZR_REVERSAL_FB_OFFSET2							UPDATES_JFZR_REVERSAL_FB_OFFSET2
#define JFZR_REVERSAL_FB_OFFSET3___							0x0000001C

// 疲劳值
#define JFZR_REVERSAL_FATIGUE_OFFSET						UPDATES_JFZR_REVERSAL_FATIGUE_OFFSET

// 当前城镇名称
#define JFZR_REVERSAL_VILLAGE_NAME_OFFSET					UPDATES_JFZR_REVERSAL_VILLAGE_NAME_OFFSET
#define JFZR_REVERSAL_VILLAGE_NAME_LEN_OFFSET____			UPDATES_JFZR_REVERSAL_VILLAGE_NAME_OFFSET+0x14

// HOOK 收包地址
#define JFZR_REVERSAL_RECV_UN_PACKET_HOOK					UPDATES_JFZR_REVERSAL_RECV_UN_PACKET_HOOK    
#define JFZR_REVERSAL_RECV_UN_PACKET_CODE					0x8B,0x45,0xC8,0x2B,0x45,0xC4

// 表示角色在城镇或者图内	hook 00817830    B9 01000000     MOV ECX,0x1,取EAX值	
// bool bflag = [EAX+4]; if( bflag == 1 ) 角色在城镇 if( bflag == 0 ) 角色在图内
// #define JFZR_REVERSAL_ROLE_WHERE_THE_MAP_HOOK				UPDATES_JFZR_REVERSAL_ROLE_WHERE_THE_MAP_HOOK
// #define JFZR_REVERSAL_ROLE_WHERE_THE_MAP_FLAG_OFFSET___		0x4

// 遍历很多对象表的首地址（目前用于"GetActiveQuests"），用于hook，取ECX的值
#define JFZR_REVERSAL_ALLOBJ_MAP_FIND_ADDR_HOOK				UPDATES_JFZR_REVERSAL_ALLOBJ_MAP_FIND_ADDR_HOOK
#define JFZR_REVERSAL_ALLOBJ_MAP_FIN_ADDR_OFFSET			UPDATES_JFZR_REVERSAL_ALLOBJ_MAP_FIN_ADDR_OFFSET
#define JFZR_REVERSAL_ALLOBJ_MAP_FUND_CODE					0x8D,0x55,0x10,0x52,0x57


// 当前职业任务对象，判断任务是否可接的第一个判断
#define JFZR_REVERSAL_TASK_OBJ_ADDR1						UPDATES_JFZR_REVERSAL_TASK_OBJ_ADDR1
#define JFZR_REVERSAL_TASK_OBJ_OFFSET2						UPDATES_JFZR_REVERSAL_TASK_OBJ_OFFSET2

// 任务数量比当前职业任务对象多3倍，猜测为所有职业任务对象，通过遍历此表，返回任务的NPC对象，即接任务的NPC对象名称
#define JFZR_REVERSAL_TASK_OBJ_ADDR2						UPDATES_JFZR_REVERSAL_TASK_OBJ_ADDR2   

// 已接任务对象 Received task
#define JFZR_REVERSAL_RECEIVED_TASK_OBJ_OFFSET1				UPDATES_JFZR_REVERSAL_RECEIVED_TASK_OBJ_OFFSET1
#define JFZR_REVERSAL_RECEIVED_TASK_OBJ_OFFSET2				UPDATES_JFZR_REVERSAL_RECEIVED_TASK_OBJ_OFFSET2
#define JFZR_REVERSAL_RECEIVED_TASK_OBJ_OFFSET3				UPDATES_JFZR_REVERSAL_RECEIVED_TASK_OBJ_OFFSET3
#define JFZR_REVERSAL_RECEIVED_TASK_OBJ_OFFSET4				UPDATES_JFZR_REVERSAL_RECEIVED_TASK_OBJ_OFFSET4

#define JFZR_REVERSAL_SINGLE_TASK_OBJ_OFFSET1				UPDATES_JFZR_REVERSAL_SINGLE_TASK_OBJ_OFFSET1
#define JFZR_REVERSAL_SINGLE_TASK_OBJ_OFFSET2				UPDATES_JFZR_REVERSAL_SINGLE_TASK_OBJ_OFFSET2
#define JFZR_REVERSAL_SINGLE_TASK_OBJ_OFFSET3				UPDATES_JFZR_REVERSAL_SINGLE_TASK_OBJ_OFFSET3
#define JFZR_REVERSAL_SINGLE_TASK_OBJ_OFFSET4___			0x4


// 激活状态的条件，已接任务的需求
#define JFZR_REVERSAL_TASK_ACTIVE_CONDITION_OFFSET___			0x30
// NPC对象包含可接任务对象
#define JFZR_REVERSAL_TASK_NPC_ACCPET_QUEST_OFFSET___			0x58
// NPC对象包含已接任务
#define JFZR_REVERSAL_TASK_NPC_RECEIVED_QUEST_OFFFSET___		0x68		// received
// NPC对象包含可完成任务对象
#define JFZR_REVERSAL_TASK_NPC_COMPLETE_QUEST_OFFSET___			0x78
// 任务条件，需要遍历职业任务对象
#define JFZR_REVERSAL_TASK_ACCEPT_NPC_OBJ_OFFSET___				0xFC
// 接收任务条件
#define JFZR_REVERSAL_TASK_ACCPET_CONDITION_OFFSET___			0x144
// 完成任务条件
#define JFZR_REVERSAL_TASK_COMPLETE_CONDITION_OFFSET___			0x278
// 任务奖励
#define JFZR_REVERSAL_TASK_QUEST_REWARD_OFFSET___				0x498
// 接收传送
#define JFZR_REVERSAL_TAKS_ACCEPT_TELEPORT_OFFSET___			0x698

// 判断当前角色是在城镇或者副本，且副本等级，及副本内所有房间数据
#define JFZR_REVERSAL_LOCAL_MAP_OBJ_HOOK						UPDATES_JFZR_REVERSAL_LOCAL_MAP_OBJ_HOOK
#define JFZR_REVERSAL_LOCAL_MAP_OBJ_OFFSET						UPDATES_JFZR_REVERSAL_LOCAL_MAP_OBJ_OFFSET

// 中英文映射基址
#define JFZR_REVERSAL_CHINESE_ENGLISH_MAP_ADDR					UPDATES_JFZR_REVERSAL_CHINESE_ENGLISH_MAP_ADDR
#define JFZR_REVERSAL_CHINESE_ENGLISH_MAP_OFFSET___				0x3C
#define JFZR_REVERSAL_CHINESE_ENGLISH_MAP_CALL___				0

#define JFZR_REVERSAL_SKILL_SP_OFFSET1___				0x70
#define JFZR_REVERSAL_SKILL_SP_OFFSET2___				0x4C
#define JFZR_REVERSAL_SKILL_SP_INDEX_OFFSET___			0x1DE	

// 游戏环境判断
#define JFZR_REVERSAL_GAME_CONDITION_HOOK						UPDATES_JFZR_REVERSAL_GAME_CONDITION_HOOK

#define JFZR_REVERSAL_WND_PROC_OFFSET1___						0x78  
#define JFZR_REVERSAL_WND_PROC_CALL								UPDATES_JFZR_REVERSAL_WND_PROC_CALL   


//#define JFZR_REVERSAL_CREATE_WINDOWN_EX_HOOK					UPDATES_JFZR_REVERSAL_CREATE_WINDOWN_EX_HOOK
#define JFZR_REVERSAL_CLASS_CLASSTYPE_ADDR						UPDATES_JFZR_REVERSAL_CLASS_CLASSTYPE_ADDR  

// 代码动态更新基址部分
// 此函数地址有可能会失效
#define JFZR_REVERSAL_SDB_BASE_ADDR_UP_DATA_HOOK			UPDATES_JFZR_REVERSAL_SDB_BASE_ADDR_UP_DATA_HOOK  

// 模板
#define JFZR_REVERSAL_SDB_SKILL_ADDR						UPDATES_JFZR_REVERSAL_SDB_SKILL_ADDR   	// Skills 
#define JFZR_REVERSAL_SDB_ITEM_INFO_ADDR					UPDATES_JFZR_REVERSAL_SDB_ITEM_INFO_ADDR   	// Items 
#define JFZR_REVERSAL_SDB_STAGE_INFO_ADDR					UPDATES_JFZR_REVERSAL_SDB_STAGE_INFO_ADDR   	// Stage
#define JFZR_REVERSAL_SHOP_INFO_SELL_ITEM_ADDR				UPDATES_JFZR_REVERSAL_SHOP_INFO_SELL_ITEM_ADDR   	// ShopInfos
#define JFZR_REVERSAL_CLASS_INFO_ADDR						UPDATES_JFZR_REVERSAL_CLASS_INFO_ADDR 		// Class
#define JFZR_REVERSAL_REGION_INFO_ADDR						UPDATES_JFZR_REVERSAL_REGION_INFO_ADDR 		// Region 
#define JFZR_REVERSAL_PROJECTILE_ADDR						UPDATES_JFZR_REVERSAL_PROJECTILE_ADDR		// Projectile

// 模板类之偏移
#define JFZR_REVERSAL_SDB_STAGE_INFO_IS_ARENA_STAGE_OFFSET___			0x3CA
// 018F5504 ItemOptionNameInfos		物品属性id

// 基址无特征码部分

// 副本内NPC对象销毁时机		ECX 为对象地址
#define JFZR_REVERSAL_NPC_OBJ_DESTRUCTOR_HOOK				UPDATES_JFZR_REVERSAL_NPC_OBJ_DESTRUCTOR_HOOK
// 角色销毁时机		ECX 为对象地址
#define JFZR_REVERSAL_PLAER_OBJ_DESTRUCTOR_HOOK				UPDATES_JFZR_REVERSAL_PLAER_OBJ_DESTRUCTOR_HOOK

// ProjectileSerial 获取的基址和CALL
#define JFZR_REVERSAL_PROJECTILE_SERIAL_CALL				UPDATES_JFZR_REVERSAL_PROJECTILE_SERIAL_CALL
#define JFZR_REVERSAL_PROJECTILE_SERIAL_ADDR				UPDATES_JFZR_REVERSAL_ROLE_SKILL_RUN_SERIAL_ADDR
// ElementalAttribute
#define JFZR_REVERSAL_ELEMENTAL_ATTRIBUTE_ADDR				UPDATES_JFZR_REVERSAL_ELEMENTAL_ATTRIBUTE_ADDR-4

//////////////////////////////////////////////////////////////////////////////////////////////////
// 测试使用的基址

#define JFZR_REVERSAL_USESKILL_HIT_HASH_STRING_HOOK			UPDATES_JFZR_REVERSAL_USESKILL_HIT_HASH_STRING_HOOK

/////////////////////////////////////////////////////////////////////////////////////////////////
// 10.30不删档测试增加基址，宏的名字可能根据分析数据更改
#define JFZR_REVERSAL_GET_SKILL_OBJ_ADDR_CALL				UPDATES_JFZR_REVERSAL_GET_SKILL_OBJ_ADDR_CALL
#define JFZR_REVERSAL_LOCAL_CITY_OBJ_HOOK					UPDATES_JFZR_REVERSAL_LOCAL_CITY_OBJ_HOOK
#define JFZR_REVERSAL_TIME_STAMP_HOOK						UPDATES_JFZR_REVERSAL_TIME_STAMP_HOOK
#define JFZR_REVERSAL_TIME_STAMP_OFFSET						UPDATES_JFZR_REVERSAL_TIME_STAMP_OFFSET
#define JFZR_REVERSAL_VALIDATION_DATA_CALL					UPDATES_JFZR_REVERSAL_VALIDATION_DATA_CALL  // ValidationData
#define JFZR_REVERSAL_SKILL_HIT_HASH_ADDR					UPDATES_JFZR_REVERSAL_SKILL_HIT_HASH_ADDR
#define JFZR_REVERSAL_LOCAL_PREV_ACTION_PLAY_TIME_HOOK		UPDATES_JFZR_REVERSAL_LOCAL_PREV_ACTION_PLAY_TIME_HOOK
#define JFZR_REVERSAL_LOCAL_PREV_ACTION_PLAY_TIME_OFFSET1	UPDATES_JFZR_REVERSAL_LOCAL_PREV_ACTION_PLAY_TIME_OFFSET1
#define JFZR_REVERSAL_LOCAL_PREV_ACTION_PLAY_TIME_OFFSET2	UPDATES_JFZR_REVERSAL_LOCAL_PREV_ACTION_PLAY_TIME_OFFSET2
#define JFZR_REVERSAL_LOCAL_PREV_ACTION_PLAY_TIME_OFFSET3	UPDATES_JFZR_REVERSAL_LOCAL_PREV_ACTION_PLAY_TIME_OFFSET3
#define JFZR_REVERSAL_GET_SPEED_CALL						UPDATES_JFZR_REVERSAL_GET_SPEED_CALL
#define JFZR_REVERSAL_GET_ATTACK_SPEED_ADDR					UPDATES_JFZR_REVERSAL_GET_ATTACK_SPEED_ADDR
#define JFZR_REVERSAL_GET_MOVE_SPEED_ADDR					UPDATES_JFZR_REVERSAL_GET_MOVE_SPEED_ADDR
#define JFZR_REVERSAL_GET_EVADE_RATING_ADDR					UPDATES_JFZR_REVERSAL_GET_EVADE_RATING_ADDR
#define JFZR_REVERSAL_GET_SPEED_OFFSET						UPDATES_JFZR_REVERSAL_GET_SPEED_OFFSET

/*++
00D3EAE2    8945 FC         MOV DWORD PTR SS:[EBP-0x4],EAX
00D3EAE5    8975 EC         MOV DWORD PTR SS:[EBP-0x14],ESI
00D3EAE8    C645 FC 01      MOV BYTE PTR SS:[EBP-0x4],0x1
00D3EAEC    3946 1C         CMP DWORD PTR DS:[ESI+0x1C],EAX
00D3EAEF    74 17           JE SHORT JFZR1.00D3EB08
00D3EAF1    8D4E 1C         LEA ECX,DWORD PTR DS:[ESI+0x1C]
00D3EAF4    FF15 3C144001   CALL DWORD PTR DS:[0x140143C]            ; msvcp100.?isfx@?$basic_istream@_WU?$char_traits@_W@std@@@std@@QAEXXZ

8945??8975??C645????3946??74??8D4E??FF15
--*/
#define JFZR_REVERSAL_GET_LOCAL_ROOM_POSITION_HOOK				UPDATES_JFZR_REVERSAL_GET_LOCAL_ROOM_POSITION_HOOK



#define JFZR_REVERSAL_GET_LOCAL_ROOM_POSITION_OFFSET___			0x178
#define JFZR_REVERSAL_GET_DIRECTION_CALL						UPDATES_JFZR_REVERSAL_GET_DIRECTION_CALL	// 011CDCB9    E8 7D3FFFFF     CALL JFZR.011C1C3B

// 无敌
#define JFZR_REVERSAL_WUDI_CODE_ADDR___		0x00C26698
