//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Console.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDD_DLG_ACCOUNT                 310
#define IDD_DLG_SETTING                 311
#define IDR_MENU_ACCOUNT_LIST           312
#define IDD_DLG_TEST                    313
#define IDD_DLG_MAIN                    314
#define IDD_DLG_LOGIN                   315
#define IDD_DLG_REG                     316
#define IDD_DLG_ADD_ACCOUNT_HELPER      318
#define IDD_DLG_SET_SCRIPT              319
#define IDR_MENU_ACCOUNT_LIST_ALL       320
#define IDD_DLG_SELECT_SERVICE          322
#define IDD_DLG_AUTO_RUN_SCRIPT         323
#define IDD_DLG_CRACK_CAPTCHA_SET_ACCOUNT 324
#define IDD_DLG_CRACK_CATPCHA_SET_SERVICE_INFO 325
#define IDD_DLG_CHECK_SERVER_INFO       326
#define IDD_DLG_SET_MAX_LOGIN           327
#define IDD_DLG_MGR_AC                  328
#define IDD_DLG_SELECT_GAME_AC_TYPE     329
#define IDD_DLG_TRADE                   330
#define IDD_DLG_PAGE_SKILL              331
#define IDD_DLG_PAGE_GAME_OBJS          332
#define IDD_DLG_PAGE_ITEMS              333
#define IDD_DLG_PAGE_ROOM_INFO          334
#define IDD_DLG_PAGE_TASK               335
#define IDD_DLG_MSG_BOARD               336
#define IDC_EDIT_GAME_PATH              1001
#define IDC_BT_GAME_PATH                1002
#define IDC_LIST_ACCOUNT_INFO           1003
#define IDC_BT_LOAD_LIB                 1008
#define IDC_BT_UNLOAD_LIB               1009
#define IDC_STATIC_LOAD_LIB             1010
#define IDC_EDIT_LOAD_LIB               1011
#define IDC_BT_OPE_LIB                  1012
#define IDC_BT_CALL_LUA_FUNCTION        1014
#define IDC_BT_RELOAD_LUA               1015
#define IDC_BT_FLUSH_TO_TEMP_FILE       1016
#define IDC_BT_RUN_SCRIPT               1017
#define IDC_BT_TERMINATE_SCRIPT         1018
#define IDC_LIST_GAME_INFO              1019
#define IDC_EDIT_MAIN_GAME_PATH         1020
#define IDC_BT_MAIN_SET_GAME_PATH       1021
#define IDC_EDIT_REG_KEY                1022
#define IDC_EDIT_LOGIN_ACCOUNT          1023
#define IDC_EDIT_LOGIN_PASSWORD         1024
#define IDC_EDIT_REG_CONFIRM_PASSWORD   1025
#define IDC_EDIT_REG_QQ                 1026
#define IDC_EDIT_REG_ACCOUNT            1027
#define IDC_EDIT_REG_PASSWORD           1028
#define IDC_EDIT_PAY_CONFIRM_ACCOUNT    1029
#define IDD_DLG_PAY                     1029
#define IDC_EDIT_PAY_CARD_SERIAL        1030
#define IDC_EDIT_PAY_CARD_PASSWORD      1031
#define IDC_EDIT_PAY_THE_ACCOUNT        1032
#define IDC_BT_REMOVE_BIND              1033
#define IDC_EDIT_ACCOUNT_GAME_PATH      1034
#define IDC_BT_AACOUNT_SELECT_GAME_PATH 1035
#define IDC_EDIT_ADD_THE_ACCOUNT        1036
#define IDC_EDIT_ADD_THE_PASSWORD       1037
#define IDC_COMBO_SELECT_SCRIPT         1041
#define IDC_DLG_TEXT_COMBO_SELECT_ACCOUNT 1043
#define IDC_COMBO_SELECT_SERVICE        1044
#define IDC_COMBO_AUTO_RUN_SCRIPT       1045
#define IDC_COMBO_CRACK_CAPTCHA         1046
#define IDC_EDIT_CRACK_CATPCHA_ACCOUNT  1047
#define IDC_EDIT_CRACK_CAPTCHA_PASSWORD 1048
#define IDC_EDIT_CRACK_CATPCHA_REMOTE_PORT 1049
#define IDC_EDIT_MSG_BOARD              1050
#define IDC_IPADDR_CRACK_CAPTCHA        1051
#define IDC_IPADDRESS_CHECK_SERVER      1052
#define IDC_BT_SET_MAX_LOGIN            1054
#define IDC_EDIT_SET_MAX_LOGIN          1055
#define IDC_BT_AC_AC_MGR                1056
#define IDC_BT_IMPORT_AC                1057
#define IDC_BT_EXPORT_AC                1058
#define IDC_COMBO_ADD_AC_SELECT_SERVICE 1060
#define IDC_BT_TEST_GET_PLAYERS_INFO    1061
#define IDC_LIST_TEST_PLAYERS_INFO      1062
#define IDC_BT_TEST_LOGIN_SUCCEED       1063
#define IDC_EDIT_TEST_PLAYERS_CNT       1064
#define IDC_EDIT_TEST_ITEM_TOTAL_CNT    1065
#define IDC_LIST_TEST_ITEM_INFO         1066
#define IDC_BT_TEST_GET_ITEMS_INFO      1067
#define IDC_COMBO_SELECT_GAME_AC_TYPE   1068
#define IDC_IPADDRESS_STORED_IP         1070
#define IDC_LIST_TRADE_MY_OFFER_LIST    1071
#define IDC_LIST_TRADE_OTHER_OFFER_ITEMS 1072
#define IDC_BT_GET_MY_OFFER_LIST        1073
#define IDC_BT_GET_OTHER_OFFER_ITEMS    1074
#define IDC_EDIT_TRADE_MY_OFFER_LIST_CNT 1075
#define IDC_EDIT_TRADE_OTHER_OFFER_ITEMS_CNT 1076
#define IDC_BT_SHOW_ALL_OPER_MENU       1077
#define IDC_BT_OK_STORETD_IP            1078
#define IDC_CHECK_USE_OLD_FORMAT        1079
#define IDC_BT_RUN_FIRST_SCRIPT         1080
#define IDC_EDIT_CUR_NOTIFY_AC          1081
#define IDC_LIST_SKILL_INFO             1084
#define IDC_LIST_GAME_OBJS              1085
#define IDC_EDIT_GAME_OBJS_TOTAL_CNT    1086
#define IDC_EDIT_SKILLS_TOTAL_CNT       1087
#define IDC_BT_REFRESH_SKILL_INFO       1088
#define IDC_BT_REFRESH_GAME_OBJS        1089
#define IDC_EDIT_PAGE_ITEM_TOTAL_CNT    1090
#define IDC_BT_REFRESH_PAGE_ITEMS       1091
#define IDC_LIST_PAGE_ITEMS             1092
#define IDC_LIST_PAGE_ROOM_INFO         1094
#define IDC_LIST_PAGE_TASK              1095
#define IDC_BT_REFRESH_ROOM_INFO        1096
#define IDC_COMBO_ROLE_MAX_CNT          1097
#define IDC_EDIT_LOGIN_DELAY            1098
#define ID_MENU_BEGIN                   32772
#define ID_MENU_STOP                    32774
#define ID_MENU_ADD_ACCOUNT             32777
#define ID_MENU_DELETE_ACCOUNT          32778
#define ID_MENU_LOGIN                   32780
#define ID_MENU_REG                     32781
#define ID_MENU_LIST_SHOW_GAME_WINDOW   32781
#define ID_MENU_PAY                     32782
#define ID_MENU_LIST_SET_SCRIPT         32782
#define ID_MENU_SHOW_ACCOUNT_INFO       32783
#define ID_MENU_SHOW_ALL_ACCOUNT_INFO   32784
#define ID_MENU_START_ALL_SCRIPT        32787
#define ID_MENU_STOP_ALL_SCRIPT         32788
#define ID_MENU_CLOSE_PROCESS           32789
#define ID_MENU_CLOSE_ALL_PROCESS       32790
#define ID_Menu_BEGIN_LOGIN             32792
#define ID_Menu_SELECT_SERVICE          32794
#define ID_Menu_LOGIN_SOME_GAME         32796
#define ID_Menu_AUTO_RUN_SCRIPT         32798
#define ID_Menu_ALL_AUTO_RUN_SCRIPT     32800
#define ID_Menu_STOP_LOGIN_ALL          32802
#define ID_Menu_SELECT_GAME_AC_TYPE     32806
#define ID_Menu_AS_NOTIFY_OBJ           32808
#define ID_Menu_CancelProhibit          32810
#define ID_Menu_NOTIFY_AS_THIS          32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        336
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
