#pragma once
/*
@author zhp
@date 2016/12/5 16:22
@purpose config
*/

#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif

#ifndef wxLUA_USEBINDING_FLAG_
#define wxLUA_USEBINDING_FLAG_

#define wxLUA_USEBINDING_WXGL  1
#define wxLUA_USEBINDING_WXSTC  1
#define wxLUA_USEBINDING_WXXRC  1
#define wxLUA_USEBINDING_WXRICHTEXT  1
#define wxLUA_USEBINDING_WXPROPGRID  0
#define wxLUA_USEBINDING_WXHTML  1
#define wxLUA_USEBINDING_WXMEDIA  1
#define wxLUA_USEBINDING_WXAUI  1
#define wxLUA_USEBINDING_WXADV  1
#define wxLUA_USEBINDING_WXCORE  1
#define wxLUA_USEBINDING_WXXML  1
#define wxLUA_USEBINDING_WXNET  1
#define wxLUA_USEBINDING_WXBASE  1

#endif	//wxLUA_USEBINDING_FLAG_
